Mellanox/mstflint

- flint/subcommands.cpp
- kernel/mst_main.c
Various fixes spotted by cppcheck.
> Fix cppcheck errors

- flint/subcommands.cpp
- kernel/mst_main.c
Will be aligned with  master devel
> Revert "Fix cppcheck errors"

- mvpd/mvpd.c
Description:mstvpd tool failed on CX5_SD device
Issue:1605690
> Title:mstvpd failed on CX5 Socket Direct device on RHEL 8

- mstflint.spec.in
@DanGoldbergMellanox  please review and merge
> Fixing buildng mstflint on sles . Bug#:1708590

- mtcr_ul/mtcr_ul_com.c
Description: Increment value of array pointer fixed.
Issue: None
> mstregdump - SEGFAULT fix with CX-5

- configure.ac
- mstflint.spec.in
- tracers/Makefile.am
- tracers/fwtrace/Makefile.am
- tracers/fwtrace/fw_trace_utilities.py
- tracers/fwtrace/mstfwtrace.py
- tracers/fwtrace/secure_fw_trace.py
@DanGoldbergMellanox  please review
> Port fwtrace as mstfwtrace - secure fw flow only

- tracers/fwtrace/mstfwtrace.py
@DanGoldbergMellanox Please review
> Fixing mstfwtrace bugs - 1733532, 1733543, 1733576

- tools_layouts/prm_adb_db.cpp
- tools_layouts/prm_adb_db.h
@DanGoldbergMellanox Please review
> Fix build issues in freebsd due to boost lib

- Makefile.am
- configure.ac
- tools_layouts/Makefile.am
@DanGoldbergMellanox Please review..
> Update flag name from enable-prm-genaric-tools flag to enable-adb-genaric-tools

- adb_parser/adb_parser.cpp
@DanGoldbergMellanox please review and merge
This issue also can be fixed by making with:
(make -j4 CXXFLAGS="-Wno-format-security")
> Fix format security issue for ununtu

- adb_parser/Makefile.am
- adb_parser/adb_parser.cpp
- configure.ac
- mlxreg/Makefile.am
- mlxreg/mlxreg_ui.cpp
- mstflint.spec.in
@DanGoldbergMellanox Please review and merge
> Fix issues with catching problem and add mstreg to specs file

- adb_parser/adb_parser.cpp
- tracers/fwtrace/fw_trace_utilities.py
@DanGoldbergMellanox please review and merge
> Fix issues in adb_parser and fw utilities - 1751157 and 1751189

- cmdif/Makefile.am
- cmdif/icmd_cif_open.c
- cmdif/icmd_cif_open.h
- common/Makefile.am
- dev_mgt/Makefile.am
- mtcr_ul/Makefile.am
- reg_access/Makefile.am
- tools_layouts/Makefile.am
- tools_layouts/icmd_layouts.c
- tools_layouts/icmd_layouts.h
Description:
MSTFlint support for ibdump tool.
Issue: 1533113
> Title: MSTFlint support for ibdump tool.

- configure.ac
@DanGoldbergMellanox please review and merge.
> fix configure to fail if using disable openssl with enable adb - 1753362

- small_utils/Makefile.am
- small_utils/mlxpci_lib.py
- small_utils/mstfwreset.py
Description: port mstfwreset
Issue: 1762111
> Title: port mstfwreset

- Makefile.am
- mlxfwupdate/mlxfwmanager.h
Description: add missing pldmlib to make file, Fix compile with
local iniparser
issue:1767293
issue:1767646
> Title: fix mlxfwupdate compilation errors

- configure.ac
Description: Contact changed from Arian to Eran
Issue: None
> Title: configure.ac AC_INIT fix

- configure.ac
- mlxlink/Makefile.am
- mlxlink/mlxlink_main.cpp
- mlxlink/modules/Makefile.am
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_logger.cpp
- mlxlink/modules/mlxlink_logger.h
- mlxlink/modules/mlxlink_maps.cpp
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_ui.h
- mlxlink/modules/mlxlink_user_input.cpp
- mlxlink/modules/mlxlink_user_input.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
- mlxlink/modules/printutil/Makefile.am
- mlxlink/modules/printutil/mlxlink_cmd_print.cpp
- mlxlink/modules/printutil/mlxlink_cmd_print.h
- mlxlink/modules/printutil/mlxlink_record.cpp
- mlxlink/modules/printutil/mlxlink_record.h
> Title: Adding mstlink to mstflint

- configure.ac
- mlxlink/Makefile.am
- mlxlink/mlxlink_main.cpp
- mlxlink/modules/Makefile.am
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_logger.cpp
- mlxlink/modules/mlxlink_logger.h
- mlxlink/modules/mlxlink_maps.cpp
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_ui.h
- mlxlink/modules/mlxlink_user_input.cpp
- mlxlink/modules/mlxlink_user_input.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
- mlxlink/modules/printutil/Makefile.am
- mlxlink/modules/printutil/mlxlink_cmd_print.cpp
- mlxlink/modules/printutil/mlxlink_cmd_print.h
- mlxlink/modules/printutil/mlxlink_record.cpp
- mlxlink/modules/printutil/mlxlink_record.h
@DanGoldbergMellanox ,
Can you review and merge?
> Title: mstlink porting

- configure.ac
- mlxconfig/Makefile.am
Description: Fix sqlite3, inband and boost_regex link errors
Issue: 1769359
> Title: Fix static compile of mstflint

- mlxlink/modules/mlxlink_commander.cpp
Description: Add missing exception reference
issue:N/A
> Title: fix compile error with mstlink

- tools_layouts/prm_adb_db.cpp
- tools_layouts/prm_adb_db.h
@DanGoldbergMellanox Please review this commit
> Port prm adb db header file

- fw_comps_mgr/fw_comps_mgr.cpp
Description:There are cases when it is required to re-activate a running FW
Issue:1730758
> Title:Fail Safe image reactivation after debug session

- mlxlink/modules/mlxlink_commander.cpp
> Title: Fixing phy port state

- mstflint.spec.in
Description: version and contact detailes update in spec file
Issue: 1754739
> Title: mstflint version fixed when installation is via rpm build

- mlxlink/modules/mlxlink_commander.cpp
> Title: Fixing setting port FEC and change port down error message

- mlxlink/modules/mlxlink_ui.cpp
> Title: Fixing code review for [pull request 129]

- mstflint.spec.in
> Title: In change log fwtrace renamed to mstfwtrace

- flint/cmd_line_parser.cpp
- flint/err_msgs.h
- flint/subcommands.cpp
- flint/subcommands.h
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
Description:Adding -ir flag to flint (automatic reactivation before burn)
Issue:1730758
> Title:Fail Safe image reactivation part 3

- flint/subcommands.cpp
Description:Burn image with -image_reactivation flag, showing wrong FW version
Issue:1776050
> Title:Fixing bugs related to IR flags and current FW version displaying

- mstdump/crd_main/mstdump.c
> Title: tool name fix when running 'mstregdump -v'

- tracers/fwtrace/mstfwtrace.py
Description: set fwtrace to work on non-secure fw.
Issue: 1795189
> Title: 1795189: support for fwtrace also in non-secured mode.

- kernel/mst_main.c
Description: Adding the identifier of ConnectX6 and ConnectX6DX.
> Create ConnectX6 and ConnectX6 DX devices in mstflint.

- configure.ac
- mlxconfig/Makefile.am
- mlxfwupdate/Makefile.am
Fix build issue in freeBSD platform when using flag '--enable-fw-mgr' in ./configure step
Description: include path added in configure.ac for libxml2 xpath.h header.
Issue: 1755019
> Fix build issue in freeBSD

- mlxarchive/mlxarchive.cpp
- mlxarchive/mlxarchive_mfa2_utils.cpp
- mlxarchive/mlxarchive_mfa2_utils.h
Description: Error message changed.
Issue: 1601757
> mstarchive error message fix when the output file provided is a directory

- reg_access/reg_access.c
- tools_layouts/reg_access_hca_layouts.c
- tools_layouts/reg_access_hca_layouts.h
Description: Registers mqis, mcqi structs updated
Issue: 1903342
> mstflint seg fault fix

- reg_access/reg_access.c
- tools_layouts/adb/prm/hca/ext/register_access_table.adb
- tools_layouts/adb/prm/switch/ext/register_access_table.adb
- tools_layouts/reg_access_hca_layouts.c
- tools_layouts/reg_access_hca_layouts.h
Description: reg access and tools layouts updated and fixed the issue.
Issue: 1908783
> Fix - mstflint burn fails with seg fault

- small_utils/mlxfwresetlib/Makefile.am
- small_utils/mlxfwresetlib/cmd_reg_mfrl.py
- small_utils/mlxfwresetlib/cmd_reg_mpcir.py
- small_utils/mlxfwresetlib/mlxfwreset_mlnxdriver.py
- small_utils/mstfwreset.py
Description:Fix mstfwreset Bug:1908440 and copy missing files in mstfwreset
Issue:1908440
> Title:Fix mstfwreset Bug:1908440 and copy missing files in mstfwreset

- mlxreg/mlxreg_ui.cpp
> Fix mstreg access type field display

- mstflint.spec.in
> Bad date fix in change log

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
Description: None
Issue: None
Signed-off-by: 
Mustafa Dalloul <mustafadall@mellanox.com>
> Fixing port speed configuration for new devices

- mlxarchive/mlxarchive_mfa2_extension.cpp
> Fix - mstarchive sprintf caused seg fault on some OSs

- flint/cmd_line_parser.cpp
- flint/flint.cpp
- flint/flint_params.cpp
- flint/flint_params.h
- flint/subcommands.cpp
- flint/subcommands.h
- mflash/mflash.c
- mflash/mflash.h
- mflash/mflash_pack_layer.h
- mlxfwops/lib/flint_io.cpp
- mlxfwops/lib/fs2_ops.cpp
- mlxfwops/lib/fs2_ops.h
- mlxfwops/lib/fs3_ops.cpp
- mlxfwops/lib/fs3_ops.h
- mlxfwops/lib/fs4_ops.cpp
- mlxfwops/lib/fs4_ops.h
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fsctrl_ops.h
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
> FW image on a device which operates in livefish mode using binary FW file

- mlxlink/modules/mlxlink_commander.cpp
> Title: fixing help message in mstlink

- flint/subcommands.cpp
> Binary compare success when update device FW but it should fails.

- cmdif/tools_cif.h
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr_dma_access.cpp
- mlxfwops/lib/fs2_ops.cpp
- mlxfwops/lib/fsctrl_ops.cpp
- mtcr_ul/mtcr_ib_ofed.c
- small_utils/mstfwreset.py
- tools_layouts/tools_open_layouts.h
lintian found some spelling mistakes. Fix them all.
> Fix spelling mistakes

- resourcedump/mstresourcedump.py
- resourcedump/resource_data/DumpData.py
- resourcedump/segments/MenuRecord.py
- resourcedump/segments/MenuSegment.py
Description: tool can handle the segment type to dump name as well.
Issue: 1765283
> resourceDump – add ability to run with segment type name.

- resourcedump/segments/MenuSegment.py
Description: add index1, index2 for supporting "0" value.
Issue: 1966366
> resourcedump - index1, index2 should support "0" value.

- resourcedump/fetchers/ResourceDumpFetcher.py
- resourcedump/mstresourcedump.py
- resourcedump/resource_data/DumpData.py
- resourcedump/segments/MenuSegment.py
- resourcedump/utils/constants.py
Description: set correct flags according the CLI convention.
Issue: 1972738
> mstresourcedump - adjust arguments and help message.

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_ui.cpp
Description:
- Fixing clear counters command
- Fixing mstlink description message
Issue: 1952770
Issue: 1917325
> Title: [mstlink] porting important fixes

- mlxlink/modules/mlxlink_commander.cpp
> [mstlink] Fixing FEC cap info for 100GbE

- mlxlink/modules/mlxlink_commander.cpp
> [mstlink] Fixing extended speed string

- mlxlink/modules/mlxlink_utils.cpp
> [mstlink] Fixing setting FEC mode

- mlxlink/modules/mlxlink_commander.cpp
> [mstlink] Fix error message while showing serdes tx

- small_utils/mstfwreset.py
> mlxfwreset - Increase the timeout to let Linux OS create config files

- reg_access/regaccess.py
> mlxfwreset send reg-access MPCIR with GET command

- configure.ac
- mstflint.spec.in
> Updating version and change-log for 4.13.3 release

- mlxlink/modules/mlxlink_commander.cpp
> Important fixes for Tigris split port and other fixes

- mlxlink/modules/mlxlink_commander.cpp
> Fixing fec speed for 100G and 25G

- mlxlink/modules/mlxlink_commander.cpp
> Fixing show external phy error message

- dev_mgt/tools_dev_types.c
> update Ardbeg_rev1 device_id

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_user_input.cpp
- mlxlink/modules/mlxlink_user_input.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
> Adding new flag to mstlink to support PRBS modulation

- tools_layouts/adb/prm/hca/ext/register_access_table.adb
- tools_layouts/reg_access_hca_layouts.c
- tools_layouts/reg_access_hca_layouts.h
> Tools layouts update according to HCA PRM

- mlxfwops/lib/bluefiled_signature_manager.cpp
- mlxfwops/lib/connectx6_signature_manager.cpp
- mlxfwops/lib/connectx6dx_signature_manager.cpp
- mlxfwops/lib/signature_manager.h
- mlxfwops/lib/signature_manager_factory.h
> MFA2 Burning missing files

- Makefile.am
> Fix mstflint compilation issue by changing compilation order of mlxarchive

- mlxreg/mlxreg_lib.cpp
Description: NCFG register added to mlxreg
Issue: 1933411
> Globally disable RoCE through mst

- dev_mgt/tools_dev_types.c
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mad_ifc/mad_ifc.c
- mad_ifc/mad_ifc.h
- mflash/mflash.c
- mlxfwops/lib/fs3_ops.cpp
- mlxfwops/lib/fs3_ops.h
- mlxfwops/lib/fsctrl_ops.cpp
- reg_access/reg_access.c
- reg_access/reg_access.h
- reg_access/regaccess.py
> MGIR reg access changed to use PRM layout instead of open layout

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_user_input.cpp
- mlxlink/modules/mlxlink_user_input.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
> Revert "Adding new flag to mstlink to support PRBS modulation"

- Makefile.am
- configure.ac
- flint/Makefile.am
- flint/subcommands.cpp
- flint/subcommands.h
Description:[Mstflint] build fail in Freebsd platform
Issue:2034606
> Fix mstflint build to include mstarchive when "enable_fw_mgr" flag is set

- flint/Makefile.am
> Fix - removed unnecessary lzma lib from flint Makefile.am

- mlxlink/Makefile.am
- mlxlink/modules/Makefile.am
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/printutil/Makefile.am
- mlxlink/modules/printutil/mlxlink_cmd_print.cpp
- mlxlink/modules/printutil/mlxlink_cmd_print.h
- mlxlink/modules/printutil/mlxlink_record.cpp
- mlxlink/modules/printutil/mlxlink_record.h
> Adding new flag "--json" to print the output in JSON format

- tracers/fwtrace/fw_trace_utilities.py
Description: add support for python3 arithmetic int division.
Issue: 2034598
> Fix 2034598 - [Mstfwtrace] throws error when run the tool with "--real_ts" flag on Sles

- mlxlink/modules/mlxlink_commander.cpp
> [mstlink] Fixing json format for valid pcie links

- mlxlink/modules/mlxlink_maps.cpp
> [mstlink] Fixing lane width for 50G PAM4

- mlxlink/modules/mlxlink_commander.cpp
> Revert "[mstlink] Fixing json format for valid pcie links"

- mlxlink/modules/mlxlink_maps.cpp
> Revert "[mstlink] Fixing lane width for 50G PAM4"

- mlxlink/modules/mlxlink_commander.cpp
> Revert "Revert "[mstlink] Fixing json format for valid pcie links""

- mlxlink/modules/mlxlink_maps.cpp
> Revert "Revert "[mstlink] Fixing lane width for 50G PAM4""

- small_utils/mstfwreset.py
> mlxfwreset debug prints for TIMING TEST

- mlxarchive/mlxarchive.cpp
> [mstarchive] Fixing tool naming in the help message

- resourcedump/segments/MenuSegment.py
Description: in case of unsupported no value will pass.
Issue: 2066225
> Fix 2066225: [resourcedump] unsupported flags with '0' value will pass.

- resourcedump/commands/QueryCommand.py
- resourcedump/fetchers/ResourceDumpFetcher.py
Description: adjust the logic of vhcaid and valid bit (for all values that user set for vhcaid parameter, valid bit will be 1).
Issue: 2080247
> Fix 2080247: resourcedump - adjust the logic of vhcaid and valid bit.

- cmdif/tools_cif.h
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr_dma_access.cpp
- mlxfwops/lib/fs2_ops.cpp
- mlxfwops/lib/fs4_ops.cpp
- mlxfwops/lib/fsctrl_ops.cpp
- mtcr_ul/mtcr_ib_ofed.c
- small_utils/mstfwreset.py
- tools_layouts/tools_open_layouts.h
lintian found spelling mistakes of `aligned`. Fix them all.
> Fix spelling mistake of "aligned"

- mlxlink/modules/mlxlink_commander.cpp
> [mstlink] Fixing memory leaks

- mlxlink/modules/mlxlink_commander.cpp
> [mstlink] Fixing checking FW when working with PCIe port

- cmdif/cmdif.py
- mtcr_py/mtcr.py
- reg_access/regaccess.py
> bug fix - python prints "b" in the error messages

- man/mstarchive.md
- man/mstconfig.md
- man/mstcongestion.md
- man/mstflint.md
- man/mstfwmanager.md
- man/mstfwreset.md
- man/mstfwtrace.md
- man/mstlink.md
- man/mstmcra.md
- man/mstmread.md
- man/mstmtserver.md
- man/mstmwrite.md
- man/mstprivhost.md
- man/mstreg.md
- man/mstregdump.md
- man/mstvpd.md
> Adding new markdown pages for mstflint tools

- small_utils/mstfwreset.py
> mstfwreset - typo fix

- tools_layouts/adb/prm/hca/ext/register_access_table.adb
- tools_layouts/reg_access_hca_layouts.c
- tools_layouts/reg_access_hca_layouts.h
> Updated tools layouts

- mlxfwupdate/cmd_line_params.cpp
- mlxfwupdate/cmd_line_parser.cpp
- mlxfwupdate/image_access.cpp
- mlxfwupdate/img_version.cpp
- mlxfwupdate/img_version.h
- mlxfwupdate/mlnx_dev.cpp
- mlxfwupdate/mlnx_dev.h
- mlxfwupdate/mlxfwmanager.cpp
- mlxfwupdate/output_fmts.cpp
- mlxfwupdate/psid_query_item.h
- mlxfwupdate/server_request.cpp
> MstFWManager Update

- small_utils/mlxpci_lib.py
> Fix mlxpci infinite loop issue

- adb_parser/adb_expr.cpp
- adb_parser/adb_expr.h
- adb_parser/adb_parser.cpp
- adb_parser/adb_parser.h
- adb_parser/expr.cpp
- adb_parser/expr.h
- mlxreg/mlxreg_parser.cpp
- mlxreg/mlxreg_parser.h
> updating adb_parser

- dev_mgt/tools_dev_types.c
- dev_mgt/tools_dev_types.h
- mflash/mflash.c
- mtcr_ul/mtcr_ul_com.c
- mtcr_ul/mtcr_ul_icmd_cif.c
> [mstflint] on Firebird failed with MFE_CR_ERROR

- mlxlink/modules/printutil/mlxlink_cmd_print.cpp
> [mstlink] Fixing printing null values in json format

- flint/subcommands.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mlxfwops/lib/connectx6dx_signature_manager.cpp
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fsctrl_ops.h
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
- mlxfwops/lib/mlxfwops_com.h
- mlxfwops/lib/signature_manager.h
> Add life cycle and secure boot indications to flint query full command for CX6 and CX6DX

- flint/subcommands.cpp
- flint/subcommands.h
> Adding MFA2 query to flint

- mlxarchive/mlxarchive_mfa2.cpp
> Querying based on a PSID in a MFA2 package not working

- mlxarchive/mlxarchive.cpp
- mlxarchive/mlxarchive.h
- mlxarchive/mlxarchive_mfa2.cpp
- mlxarchive/mlxarchive_mfa2.h
> [mstarchive] tool should not accept the same flag more than one time

- resourceparse/resource_data/RawData.py
Description: improve the data collector for json format.
Issue: 2134797
> resourceparse – upgrade the logic of devlink json format collect.

- resourcedump/segments/SegmentCreator.py
- resourceparse/segments/SegmentCreator.py
Description: improve the segment creator complexity.
Issue: 2135334
> resourcedump and resourceparse – optimization.

- kernel/mst_kernel.h
- kernel/mst_main.c
Description:
Adding a detailed message with device id, dbdf and unsupported capability.
Issue: 310
Please enter the commit message for your changes. Lines starting
> Unclear info message in case of unsupported capability.

- debian/changelog
- kernel/mstflint_kernel.spec
- mstflint.spec.in
> Revert "Updated version to 4.14.0-3. Updated changelog."

- kernel/mst_main.c
Description:
Failed to check the CR_SPACE capability due to wrong condition.
Issue: 2211966
> Mstflint driver: Failed to get space support status.

- configure.ac
- mlxlink/Makefile.am
- mlxlink/modules/Makefile.am
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/printutil/Makefile.am
> [mstlink] Fixing linking to system jsoncpp if installed

- flint/subcommands.cpp
Description:
Issue: 2275794, 2277123
> mstflint fix - export_public_key command fix + typo fix

- flint/Makefile.am
- flint/subcommands.cpp
- fw_comps_mgr/Makefile.am
> Fix build issue when using --disable-openssl at configure step

- fw_comps_mgr/Makefile.am
> Fix build on RH8 + setups

- small_utils/mlxfwresetlib/mlxfwreset_mlnxdriver.py
> mlxfwreset stop/start user-space RSHIM driver on Linux

- mlxfwops/lib/fs3_ops.cpp
Added missing piece from MFT regarding RSA features
> added RSA 4K section information

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_ui.cpp
> [mstlink] Updating help menu and adding war msg

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_eye_opener.cpp
- mlxlink/modules/mlxlink_eye_opener.h
Fixing margin tool for MH devices
Issue: 2756971
> [mstlink] Fixing margin tool for MH devices

- tools_layouts/adb/prm/hca/ext/register_access_table.adb
- tools_layouts/adb/prm/switch/ext/register_access_table.adb
- tools_layouts/reg_access_hca_layouts.c
- tools_layouts/reg_access_hca_layouts.h
- tools_layouts/reg_access_switch_layouts.c
- tools_layouts/reg_access_switch_layouts.h
- tools_layouts/register_access_open_layouts.c
Description:
HCA PRM: 0.56 I
Switch PRM: 1.55.046
> Updated PRM layouts for HCA and switch

- mlxconfig/mlxcfg_generic_commander.cpp
- mlxfwops/lib/fs3_ops.cpp
- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_amBER_collector.h
- mlxlink/modules/mlxlink_commander.cpp
- mlxreg/mlxreg_parser.cpp
- mlxreg/mlxreg_parser.h
- reg_access/regaccess.py
Description:
New adb integration for mstlink
> Adb integration for mstflint tools

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
Supporting the new SerDes TX for 7nm products.
Affected commands: [serdes_tx <params>, show_serdes_tx]Tested flows:
Issue: 2576446
> [mstlink][NDR_GEN] Supporting the new SerDes TX parameters

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/printutil/mlxlink_record.h
Adding extra module information for 7nm and 16nm products
Issue: 2483577
> [mstlink][NDR_GEN] Adding extra module information in show_module

- configure.ac
- mlxsign_lib/mlxsign_openssl_engine.cpp
merge of configure.ac openssl version test.
> fix openssl version number test for build config

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_err_inj_commander.h
- mlxlink/modules/mlxlink_port_info.h
- mlxlink/modules/mlxlink_ui.cpp
This reverts commit 8120fd218977114c490bd10a4eb98187bccfc9d0.
> Revert "align 4.18"

- small_utils/mlxfwresetlib/cmd_reg_mcam.py
- small_utils/mlxfwresetlib/cmd_reg_mfrl.py
- small_utils/mlxfwresetlib/cmd_reg_mpcir.py
- small_utils/mlxfwresetlib/mlxfwreset_mlnxdriver.py
- small_utils/mlxfwresetlib/mlxfwreset_utils.py
- small_utils/mstfwreset.py
(1) error for UEFI secure-boot
(2) Updates to error "command is not supported"
Issue:2781648,2826479
> [mlxfwreset]

- cmdif/cmdif.py
- dev_mgt/dev_mgt.py
- resourcedump/fetchers/ResourceDumpFetcher.py
- resourcedump/segments/MenuSegment.py
- resourceparse/parsers/Parser.py
- resourceparse/resource_data/DataPrinter.py
- resourceparse/resource_data/RawData.py
- resourceparse/segments/MenuSegment.py
> minor code change to supporting python 3.8 + compilation fix

- flint/subcommands.cpp
- flint/subcommands_linkx.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- mflash/mflash.c
- mlxfwops/lib/connectx6_signature_manager.cpp
- mlxfwops/lib/fs3_ops.cpp
- mlxfwops/lib/fs3_ops.h
- mlxfwops/lib/fs4_ops.cpp
- mlxfwops/lib/fs4_ops.h
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fsctrl_ops.h
- mlxfwops/lib/fuse_gw.cpp
- mlxfwops/lib/fuse_gw.h
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
- mlxfwops/lib/signature_manager.h
- mlxfwupdate/mlnx_dev.cpp
- mlxfwupdate/mlnx_dev.h
Description: Bugs fixes related to flash encryption feature
Tested OS: N/A
Tested flows: N/A
Issue: 2844452
> [flint] bugs fixes

- debian/changelog
Description: summary updated in change log file, for full documentaion see the 4.18 user manual.
> updated changelog with main features and changes in 4.18

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
Fixing PRBS BER/Errors output after performing the tuning
Issue: 2869233
> [mstlink] Fixing PRBS BER/Errors output

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_enums.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/printutil/mlxlink_record.cpp
- mlxlink/modules/printutil/mlxlink_record.h
Description:
Supporting port access for downstream devices which came with Spectrum-3
Issue: 2839979
> [mstlink] Supporting port access for downstream devices

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing label port display in csv file
Issue: 2861535
> [mstlink] Fixing label port display in csv file

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing device tech for Connect-X7
Issue: 2901548
> [mstlink] Fixing device tech for Connect-X7

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_ui.cpp
Description:
-> Fixing json format for some fields
-> Fixing error message with invalid fec_speed
-> Adding NDR speed to the help menu
-> Fixing mst pkg versioning in mstlink
Issue: 2854445
Issue: 2899194
Issue: 2902805
> [mstlink] Fixing formatting issues

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_enums.h
- mlxlink/modules/mlxlink_port_info.h
- mlxlink/modules/mlxlink_ui.cpp
Description:
-> Fixing rx prbs modes when set worng mode
-> Fixing error message when device have no valid prbs
Issue: 2824323
Issue: 2904985
> [mstlink] Fixing formatting bugs and updating amber to 1.80

- mlxlink/modules/mlxlink_utils.cpp
Fixing 400G 4X speed in show fec command
Issue: 2912099
> Fixing 400G 4X speed in show fec command

- flint/subcommands.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mlxconfig/mlxcfg_generic_commander.cpp
- mlxconfig/mlxcfg_parser.cpp
- mlxconfig/mlxcfg_ui.cpp
- mlxconfig/mlxcfg_ui.h
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/mlxfwops_com.h
- reg_access/reg_access.c
- reg_access/reg_access.h
- tools_layouts/adb/prm/switch/ext/register_access_table.adb
- tools_layouts/reg_access_switch_layouts.c
- tools_layouts/reg_access_switch_layouts.h
Merging all remote tokens related commits
> Remote tokens

- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_cables_commander.h
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
Description:
Fixing show_module and --cables flags while accessing Buffalo ports
Issue: 2921059
> Fixing cable features

- mtcr_ul/mtcr_ul_com.c
> fixed bug in mtcr reg access smp fallback

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing warning message while configuring RM loopback
Issue: None
> [mstlink] Fixing warning message while configuring RM loopback

- mlxlink/modules/mlxlink_ui.cpp
Description:
Removing un-supported port types flags
Issue: 2985558
> [mstlink][AGB] Removing un-supported port types flags

- mlxlink/modules/mlxlink_ui.cpp
Description:
Removing unneeded flags for mstlink
Issue: None
Signed-off-by: Mustafa Dalloul mustafadall@nvidia.com
> [mstlink] Removing unneeded flags for mstlink

- kernel/mstflint_kernel.spec
- mstflint.spec.in
Description:
Tested OS:
Tested flows:
Issue:
> update mstflint version to 4.19.0

- adb_parser/adb_parser.h
Description:
Tested flows: compilation
Issue: 3014307
> [adb_parser] remove irrelevant include

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing error message for invalid port
Issue: 3019487
> [mstlink] Fixing error message

- mlxconfig/mstprivhost.py
Description:
Supporting new flow for the tool to provide more isolation between
hosts in multi-host environments
Issue: 2989293
> [mstprivhost] Supporting new flow for the tool

- mlxconfig/mstprivhost.py
Fixing per host configuration
Issue: 3032958
> [mstprivhost] Fixing per host configuration

- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_cables_commander.h
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_maps.cpp
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
Description:
Fixing parsing clear_diagnostic_info and lane_rate options
Issue: 3033765
> [mstlink] Fixing parsing clear_diagnostic_info and lane_rate options

- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_cables_commander.h
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_maps.cpp
- mlxlink/modules/mlxlink_maps.h
Description:
Ignoring cap check and fixing pmcr issues
Issue: 3030730
> [mstlink][PMCR] Ignoring cap check and fixing pmcr issues

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing serdes tx configuration
Tested devices: ConnectX-7
Tested flows:
mstlink serdes_tx feature
Issue: 3070347
> [mstlink] Fixing serdes tx configuration

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing Coverity Issues
Issue: 3023527
> [mstlink] Fixing Coverity Issues

- mlxconfig/mlxcfg_db_manager.cpp
- mlxconfig/mlxcfg_db_manager.h
- mlxconfig/mlxcfg_generic_commander.cpp
- mlxconfig/mlxcfg_tlv.cpp
- mlxconfig/mlxcfg_tlv.h
Description:
[mstconfig] - updating mstconfig to mlxconfig
Tested devices: Cx7
Tested flows: mlxconfig -d {device} q
mlxconfig -d {device} s LINK_TYPE_P1=2
Issue: 3116414
> [mstconfig] - updating mstconfig to mlxconfig

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing char check fault
Issue: 3114890
> [mstlink] Fixing char check fault

- mlxlink/modules/mlxlink_amBER_collector.h
- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_reg_parser.h
- mlxlink/modules/mlxlink_utils.cpp
Description:
Fixing code coverity issues and code align with MFT
> [mstlink] Fixing code coverity issues

- include/mtcr_ul/mtcr_com_defs.h
> removed deprecated device types

- dev_mgt/tools_dev_types.c
- dev_mgt/tools_dev_types.h
- flint/subcommands.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- mflash/mflash.c
- mflash/mflash_dev_capability.c
- mflash/mflash_pack_layer.h
- mlxfwops/lib/flint_io.cpp
- mlxfwops/lib/fs2_ops.cpp
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/mlxfwops_com.h
- mlxfwupdate/mlnx_dev.cpp
- mlxfwupdate/mlxfwmanager.cpp
- mlxreg/mlxreg_lib.cpp
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
- small_utils/mstfwreset.py
- tools_res_mgmt/tools_res_mgmt.c
Description:
CX
CX-2
SwitchX
BridgeX
Infiniscale
Infinihost
> deprecation of legacy devices

- mlxlink/modules/mlxlink_reg_parser.cpp
- mlxreg/mlxreg_parser.cpp
- mlxreg/mlxreg_parser.h
- mlxreg/mlxreg_ui.cpp
- mlxreg/mlxreg_ui.h
Description:added the ability to set/get OP fields when using mlxreg.
> added --op flag to mlxreg.

- dev_mgt/dev_mgt.py
- dev_mgt/tools_dev_types.c
- dev_mgt/tools_dev_types.h
Description:
Tested OS: None
Tested devices: None
Tested flows: None
Issue: None
> [dev_mgt] rebased from mft 4.21

- resourcedump/commands/DumpCommand.py
- resourcedump/fetchers/ResourceDumpFetcher.py
- resourcedump/resource_data/DataPrinter.py
- resourcedump/resource_data/DumpData.py
- resourcedump/resource_data/QueryData.py
> [resourcedump] port changes from mft 4.21

- mlxlink/modules/mlxlink_cables_commander.cpp
Adding missing case for QSFP_CMIS cables while running ddm command,
And adding default case for un-recognized identifiers
Issue: 3174798
> [mstlink] Fixing show ddm info for QSFP_CMIS cables

- small_utils/mlxfwresetlib/pci_device.py
- small_utils/mstfwreset.py
This reverts commit cda200fa8ac6f2464125629125984d14f21e9709.
> Revert "Sync 1 as default in case of DPU and driver sync supported according to MCAM"

- mlxlink/modules/mlxlink_err_inj_commander.cpp
Description:
Fixing mixers configuration while configuring them togther
Issue: 3193164
> [mstlink] Fixing rx error injection mixers configuration

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
Description:
-> Fixing ld_down field
-> Fixing link_down counter field
Tested flows:
-> mstlink show_counter for PCIe port
-> mstlink ber_collect
Issue: 3179754
Issue: 3179769
> [mstlink] Fixing internal fields exposure on the external features

- mlxconfig/mlxcfg_generic_commander.cpp
- tools_layouts/adb/prm/hca/ext/register_access_table.adb
> update mlxconfig and tool layout with latest mft changes for 4.22

- mlxlink/modules/amber_field.cpp
- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing amber fields issues
Issue: 3170527
> [mstlink] Fixing amber fields issues

- mstdump/crd_main/mstdump.c
Description:
Tested OS:
Tested flows:
Issue: 3213932
> [mstregdump] bugfix - csv-file-path arrives NULL

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_enums.h
- mlxlink/modules/mlxlink_err_inj_commander.cpp
- mlxlink/modules/mlxlink_maps.cpp
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_utils.cpp
Description:
Updating amber to 2.08 and porting some fixes
Issue: 3195622
> [mstlink] Updating amber to 2.08 and porting some fixes

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_amBER_collector.h
Description:
Pushing amber collection fixes
Issue: 3225092
> [mstlink] Pushing amber collection fixes

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
Description:
Fixing fw version in tool info section
Issue: 3196169
> [mstlink] Fixing fw version in tool info section

- mlxlink/modules/mlxlink_amBER_collector.cpp
Description:
Fixing module info for QSFP_CMIS cables
Issue: 3228808
> [mstlink] Fixing module info for QSFP_CMIS cables

- mlxlink/modules/mlxlink_err_inj_commander.cpp
Description:
Validating error duration
Issue: 3228705
> [mstlink] Validating error duration

- configure.ac
- mstflint.spec.in
- resourcedump/Makefile.am
- resourcedump/fetchers/ResourceDumpFetcher.py
- resourcedump/resourcedump_lib/Makefile.am
- resourcedump/resourcedump_lib/resource_dump.c
- resourcedump/resourcedump_lib/resource_dump.h
Description:
Tested OS: all
Tested flows: checked compilation
Issue: 3178595
Please enter the commit message for your changes. Lines starting
> [mstresourcedump] Removing pyverbs and scapy dependencies

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing json output for PCIE eye info
Issue: 3257077
> [mstlink] Fixing json output for PCIE eye info

- configure.ac
- resourcedump/Makefile.am
- resourcedump/resourcedump_lib/Makefile.am
- resourcedump/resourcedump_lib/resource_dump.c
- resourcedump/resourcedump_lib/resource_dump.h
> [resourcedump] - Fixing explicit dependency on /mswg and bluefiled libs path

- resourceparse/parsers/AdbParser.py
- resourceparse/parsers/Parser.py
Description:
Tested OS:
Tested flows:
Issue: 3245643,3296467,3245652
Hash: 7d8bef3725
Hash: 80aedc30b8
Hash: af064cc061
Hash: 050c5ac6c8
Hash: beffec9f60
> [resourceparse] support Unlimited arrays + Print format + conditions

- mstflint.spec.in
Description: Fixing rpm build fail
Tested OS: all
Tested flows: checked compilation
Issue: 3327984
> [mstreourcedump] fixing spec file to include file only when exist

- adb_parser/adb_condVar.cpp
- adb_parser/adb_condVar.h
- adb_parser/adb_condition.cpp
- adb_parser/adb_condition.h
Description:
Tested OS:
Tested flows:
Issue: 3335672
> [adb_parser] add missing condition class files

- dev_mgt/dev_mgt.py
- dev_mgt/tools_dev_types.c
- dev_mgt/tools_dev_types.h
- reg_access/reg_access.c
- reg_access/reg_access.h
- reg_access/regaccess.py
- small_utils/mlxfwresetlib/cmd_reg_mcam.py
- small_utils/mlxfwresetlib/pci_device.py
- small_utils/mstfwreset.py
Description:Add support for switch fw reset flow
Tested OS:Linux
Tested flows:
Issue:
> feature #3117716: - Add support in Switch SW reset

- small_utils/congestion.cpp
> Aligned mstcongestion with PRM MCAM

- resourceparse/parsers/AdbParser.py
- resourceparse/parsers/Parser.py
Description:
Tested OS:
Tested flows:
Issue: 3343667
> [resourceparse] old python bugfix

- tools_layouts/Makefile.am
Description:
Tested OS:
Tested flows:
Issue: 3348156
> [tools_layout] Makefile bugfix

- resourceparse/parsers/AdbParser.py
Description:
Tested OS:
Tested flows:
Issue: 3352484
> [resourceparse] fix typo

- configure.ac
- dev_mgt/tools_dev_types.c
- include/mtcr_ul/mlx5ctl_ioctl.h
- include/mtcr_ul/mtcr_com_defs.h
- include/mtcr_ul/mtcr_mf.h
- mlxreg/mlxreg_lib.cpp
- mtcr_ul/Makefile.am
- mtcr_ul/mlx5ctl.c
- mtcr_ul/mlx5ctl.h
- mtcr_ul/mtcr_ul_com.c
- reg_access/reg_access.c
- reg_access/reg_access_macros.h
> Upstream driver support

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
Description:
Displaying more accurate modules rx and tx power readings The main affected command is show_module command
Issue: 3282615
> [mstlink] Displaying more accurate modules rx\tx power

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_enums.h
Update amber collection to version 2.11
Issue: 3380109
> [mstlink] align amber collection to version 2.11

- adb_parser/adb_condition.cpp
- adb_parser/adb_condition.h
- adb_parser/adb_field.cpp
- adb_parser/adb_field.h
- adb_parser/adb_instance.cpp
- adb_parser/adb_instance.h
- adb_parser/adb_parser.cpp
- adb_parser/adb_parser.h
Description:
Tested OS:
Tested flows:
Issue: None
> [adb_parser] porting changes for dynamic array's feature.

- configure.ac
Description:
Tested OS:
Tested flows:
Issue: 3408837
> [mstresourcedump] fix bug in OFED version detection

- debian/mstflint.install
Description:
Tested OS:
Tested flows:
Issue:
> dd etc dir to debian installation

- flint/subcommands.cpp
- flint/subcommands.h
- mlxfwops/lib/fs3_ops.cpp
- mlxfwops/lib/fs4_ops.cpp
- mlxfwops/lib/fs4_ops.h
- tools_layouts/cx4fw_layouts.c
- tools_layouts/cx4fw_layouts.h
- tools_layouts/image_layout_layouts.c
- tools_layouts/image_layout_layouts.h
Description:
Tested OS:
Tested flows:
Issue: None
> [cx4fw][image_layout] bug fix for cx4fw auto-gen code + image_layout

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
Description:
First phase to support the RTT, the second phase to support the other fields
Issue: 3430117
> [mstlink] Fixing PRTL fields

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing auto ports discovery for collecting amber info
Issue: 3412757
> [mlxlink][amber] Fixing auto ports collection for Spectrum-3

- resourceparse/parsers/AdbParser.py
- resourceparse/parsers/Parser.py
- resourceparse/segments/MenuSegment.py
- resourceparse/utils/Exceptions.py
Description:
Tested OS:
Tested flows:
Issue: 3434518
> [mstresourceparse] port error handling changes

- tools_layouts/icmd_hca_layouts.c
- tools_layouts/icmd_hca_layouts.h
- tools_layouts/image_layout_layouts.c
- tools_layouts/image_layout_layouts.h
- tools_layouts/mlxarchive_layouts.c
- tools_layouts/mlxarchive_layouts.h
- tools_layouts/mlxconfig_4th_gen_layouts.c
- tools_layouts/mlxconfig_4th_gen_layouts.h
- tools_layouts/reg_access_hca_layouts.c
- tools_layouts/reg_access_hca_layouts.h
- tools_layouts/reg_access_switch_layouts.c
- tools_layouts/reg_access_switch_layouts.h
- tools_layouts/tools_open_layouts.c
- tools_layouts/tools_open_layouts.h
(cherry picked from commit 0899ab25db166a11461c48e0315905eee5d184e6)
Signed-off-by: Alex Blago <alexbl@nvidia.com>
> align tools_layouts for 4.24

- small_utils/mstfwreset.py
This reverts commit f51cc1b8c8aa787223b832bcaf5ca8e4aba00b0b.
> Revert "Remove mlxfwreset support for BF2/BF3"

- resourceparse/parsers/AdbParser.py
- resourceparse/parsers/Parser.py
- resourceparse/utils/common_functions.py
- resourceparse/utils/constants.py
Description: 
Tested OS:
Tested flows:
Issue: None
> [resourcedump/resourceparse] port from mft 4.25

- resourceparse/parsers/Parser.py
Description:
Tested OS:
Tested flows:
Issue: 3498892
> [resourcedump] porting bugfix

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_amBER_collector.h
- mlxlink/modules/mlxlink_cables_commander.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
Description:
Updating amber to version 2.17
Issue: 3482396
> [mlxlink] Updating amber to 2.17

- mlxlink/modules/mlxlink_amBER_collector.cpp
Description:
Fixing handling register errors in amber collection
Issue: 3536206
> [mstlink] Fixing handling register errors in amber collection

- mlxlink/modules/mlxlink_enums.h
- mlxlink/modules/mlxlink_reg_parser.cpp
- mlxlink/modules/mlxlink_reg_parser.h
- mlxlink/modules/mlxlink_ui.cpp
Description:
- Fixing amber version to 2.17
- Adding a new index for PPCNT requests
Issue: 3490668
> [mstlink] Fixing amber version and new register index field

- tools_layouts/adb/prm/switch/ext/register_access_table.adb
- tools_layouts/reg_access_switch_layouts.c
- tools_layouts/reg_access_switch_layouts.h
Description:
Tested OS:
Tested flows:
Issue: None
> [tools_layouts] porting Switch PRM changes after PRM update

- tools_layouts/adb/prm/hca/ext/register_access_table.adb
- tools_layouts/icmd_hca_layouts.c
- tools_layouts/icmd_hca_layouts.h
- tools_layouts/reg_access_hca_layouts.c
- tools_layouts/reg_access_hca_layouts.h
Description:
Tested OS:
Tested flows:
Issue: None
> [tools layouts] updating tools layouts after Shomron PRM draft J2

- mlxconfig/mlxcfg_ui.cpp
> [mlxconfig] Remove unused include.

- mlxlink/modules/mlxlink_commander.cpp
Description:
Using MGIR register to read the fw version
Issue: 3525899
> [mstlink] Using MGIR to read fw info

- Makefile.am
- configure.ac
- flint/Makefile.am
- flint/subcommands.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mlxdpa/Makefile.am
- mlxdpa/mlxdpa.cpp
- mlxfwops/lib/Makefile.am
- mlxfwops/lib/components/fs_cert_ops.cpp
- mlxfwops/lib/components/fs_cert_ops.h
- mlxfwops/lib/components/fs_comps_factory.h
- mlxfwops/lib/components/fs_comps_ops.cpp
- mlxfwops/lib/components/fs_comps_ops.h
- mlxfwops/lib/components/fs_synce_ops.cpp
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
Description: aligning flint, mlxfwops, fw_comps_mgr, and make files
Tested flows: build, create container, sign and try to upload
Issue: None
> [mlxdpa] align flint to mlxdpa container

- mlxconfig/mlxcfg_generic_commander.cpp
Description: alignment of hca/switch signing
Tested flows: mlxconfig create_conf
Issue: 3192455
> [mlxconfig] alignment to signing interface for sign server and 3S

- mtcr_ul/mtcr_ul_com.c
Description:added missing Freysa device ID.
Tested OS:linux
Tested devices:n/a
Tested flows:n/a
Issue:3592243
> added Freysa device ID.

- small_utils/mlxfwresetlib/mlxfwreset_utils.py
- small_utils/mstfwreset.py
> Adding support for recognizing the mlx5ctl device in mstfwreset query

- flint/Makefile.am
- mlxconfig/Makefile.am
- mlxlink/Makefile.am
- mlxreg/Makefile.am
- small_utils/Makefile.am
Move external library dependencies to LDADD variables.
> fix dynamic linking

- adb_parser/adb_exceptionHolder.cpp
- adb_parser/adb_exceptionHolder.h
- adb_parser/adb_instance.cpp
- adb_parser/adb_instance.h
- adb_parser/adb_parser.cpp
- adb_parser/adb_parser.h
- adb_parser/adb_xml_parser.cpp
- adb_parser/adb_xml_parser.h
- reg_access/reg_access.c
- reg_access/reg_access.h
- resourcetools/mstresourcedump.py
- resourcetools/mstresourceparse.py
- resourcetools/resourcedump_lib/src/commands/dump_command.cpp
- resourcetools/resourcedump_lib/src/commands/dump_command.h
- resourcetools/resourcedump_lib/src/commands/query_command.cpp
- resourcetools/resourcedump_lib/src/commands/query_command.h
- resourcetools/resourcedump_lib/src/commands/resource_dump_command.cpp
- resourcetools/resourcedump_lib/src/commands/resource_dump_command.h
- resourcetools/resourcedump_lib/src/common/resource_dump_types.h
- resourcetools/resourcedump_lib/src/fetchers/fetcher.h
- resourcetools/resourcedump_lib/src/fetchers/reg_access_resource_dump_fetcher.cpp
- resourcetools/resourcedump_lib/src/fetchers/reg_access_resource_dump_fetcher.h
- resourcetools/resourcedump_lib/src/fetchers/reg_access_resource_dump_mkey_fetcher.cpp
- resourcetools/resourcedump_lib/src/filters/include_exclude_segments_filter.cpp
- resourcetools/resourcedump_lib/src/sdk/resource_dump_sdk.cpp
- resourcetools/resourcedump_lib/src/segments/resource_dump_segments.h
- resourcetools/resourcedump_lib/src/segments/resource_dump_segments_be.h
- resourcetools/resourcedump_lib/src/segments/resource_dump_segments_le.h
- resourcetools/segments/ResourceSegment.py
Description:
Tested OS:
Tested flows:
Issue: None
> [adb_parser] port from mft_4.27.0

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_reg_parser.cpp
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_ui.h
- mlxlink/modules/mlxlink_user_input.cpp
- mlxlink/modules/mlxlink_user_input.h
Description:
-Cleaning mlxlink_commander from any user input parameters -Moving all user input parameters to UserInput class
MSTFlint port needed: No
Tested devices: CX-6
Tested flows: mlxlink full test
Issue: 3554777
> [mlxlink] - fixing mlxlink infra

- mlxdpa/mlxdpa.cpp
- mlxfwops/lib/fs4_ops.cpp
- mlxfwupdate/mlnx_dev.cpp
Description: fixed uninitialized variables coverity issues.
Tested flows: compilation
Issue: 3657795
> coverity fixes.

- mlxlink/modules/mlxlink_commander.cpp
Description:
The port flag will take the IB port number for BW port access
Tested devices: BW00
Tested flows: mlxlink full commands
Issue: 3509849
> [mlxlink][BW00] Fixing port access for BW

- tools_layouts/adb/prm/switch/ext/register_access_table.adb
Description:
Tested OS:
Tested flows:
Issue:None
> [SWITCH][auto-gen] Updating mlxconfig_db and tools_layout

- flint/subcommands.cpp
Update to the tool name in the error message
> Update tool name in error message

- mlxfwops/lib/fw_ops.cpp
- mlxfwupdate/output_fmts.cpp
- small_utils/mstfwreset.py
porting of the following 3 commits that are in mft_4_29_0_release_cx8_bu branch in MFT repo:
https://git-nbu.nvidia.com/r/c/tools/mft/+/1114800
https://git-nbu.nvidia.com/r/c/tools/mft/+/1122821
https://git-nbu.nvidia.com/r/c/tools/mft/+/1123843
> Mstflint 4 29 0 cx8 es

- mlxreg/mlxreg_ui.cpp
- mlxreg/mlxreg_ui.h
- resourcetools/mstresourceparse.py
- resourcetools/resourceparse_lib/ResourceParseManager.py
- resourcetools/resourceparse_lib/parsers/AdbResourceParser.py
- resourcetools/resourceparse_lib/resource_data/DataPrinter.py
- resourcetools/segments/Segment.py
Description:
Support registers that forbid GET by adding --overwrite flag, which skips initial GET before SET.
Issue: 4026457
> Merge mstreg --overwrite change, resourcetools --out-dir change

- kernel/mst_kernel.h
- kernel/mst_main.c
Description: in order for the ioctl in mread4 to fail, read_pciconf must fail. read_pciconf calls the read function in a loop, and once the read function returns an error (for instance, when the address is out of range, indicating we need to switch to PCI VSC space), it updates the counter and returns it as an error, and  by that "hiding" the ADDRESS_OUT_OF_RANGE error.
modified read_pciconf and write_pciconf: in case the read/write function returns an error, first check whether its ADDRESS_OUT_OF_RANGE, and if so return -1.
Tested devices: cx8
Tested flows:
mcra /dev/mst/mt4131_pciconf0 0x5bfc74
mcra /dev/mst/mt4131_pciconf0 0x581018
Issue: 4118930
> pci-core VSC spaces separation fix

- mlxlink/modules/mlxlink_commander.cpp
Description:
Tested OS:
Tested flows:
Issue:
> [mlxlink] bug fix for wrong pnat in PPHCR reg

- dev_mgt/Makefile.am
- dev_mgt/therm_fw.c
- dev_mgt/therm_fw.h
- mstflint.spec.in
- small_utils/Makefile.am
- small_utils/mget_temp.c
- small_utils/mget_temp.h
Description:
Tested OS:
Tested flows:
Issue: None
> Add tool mget_temp

- mstflint.spec.in
- small_utils/Makefile.am
- small_utils/mget_temp.c
Description:
Tested OS:
Tested flows:
Issue: 4179894
> rename mget_temp to mstmget_temp

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
Description:
1- fix port numbering for Quantum3
2- fix power information lanes mapping
3- fix DPN to local port mapping when DPN is not specified 4- update fom measurement field name
5- add supported FEC Modes
6- fix dp_st_lane field access
> multiple fixes on mstflint

- configure.ac
- debian/changelog
- kernel/mstflint_kernel.spec
- mstflint.spec.in
Description:change version number from 4.29.0-1 to 4.29.1-1
MSTFlint port needed: No
Tested OS:
Tested flows:
Issue: 4203145
> change version number from 4.29.0-1 to 4.29.1-1

- mlxlink/modules/mlxlink_commander.cpp
> fixed typo in SLRG field

- mlxreg/mlxreg_lib/mlxreg_parser.cpp
Description:
Now indexes that are not supplied will be zero.
Issue: 4244941
> [mstreg] Remove index enforcement

- flint/cmd_line_parser.cpp
- flint/flint_params.cpp
- flint/flint_params.h
- flint/subcommands.cpp
- flint/subcommands.h
- fw_comps_mgr/fw_comps_mgr.cpp
- mft_utils/mft_utils.cpp
- mft_utils/mft_utils.h
- mlxdpa/certcontainerbase.cpp
- mlxdpa/certcontainerbase.h
- mlxdpa/certcontainerimp.cpp
- mlxdpa/certcontainerimp.h
- mlxdpa/mlxdpa.cpp
- mlxfwops/lib/components/fs_cert_ops.cpp
- mlxfwops/lib/components/fs_cert_ops.h
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fsctrl_ops.h
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
Description: After burn DPA cert to device, query the cert status, to know a BF3/CX7 has a DPA cert burnt successfully and get some information about the cert : cert_uuid, keypair_uuid, targeting type, intended use and priority.
> [flint][query components] method to query DPA cert burnt status on BF3/CX7

- small_utils/mlxfwresetlib/cmd_reg_mfrl.py
- small_utils/mlxfwresetlib/cmd_reg_mroq.py
- small_utils/mstfwreset.py
There is already another check to verify if hot reset is supported
> mlxfwreset | Remove unnecessary check for hot reset support

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_ui.cpp
Description:
Tested OS:
Tested flows:
Issue:
> mlxlink | bug fix for min port always chosen.

- README
Note that PRs should go to the branch master_devel. However, start reworking the README before that to make it easier to change it.
> README: changes from master_devel

- flint/subcommands.cpp
- flint/subcommands_linkx.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mlxconfig/mlxcfg_generic_commander.cpp
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/signature_manager_factory.h
Porting burn tools content into GB200 branch
> Burn tools sync

- flint/subcommands.cpp
Description: fixes build issues
> [flint] alignment to master_devel

- small_utils/mstfwreset.py
1. MFRL was not sent due to an uninitialized MROQ.
2. The tool incorrectly selected sync 1.
3. Sync 1 is not supported by the FW for reset level 4 (reboot).
> mlxfwreset | Fixing MFRL and Sync Issues for Reset Level 4

- adb_parser/adb_condition.cpp
- adb_parser/adb_db.cpp
- adb_parser/adb_exceptionHolder.cpp
- adb_parser/adb_exceptionHolder.h
- adb_parser/adb_field.cpp
- adb_parser/adb_field.h
- adb_parser/adb_instance.cpp
- adb_parser/adb_instance.h
- adb_parser/adb_node.cpp
- adb_parser/adb_node.h
- adb_parser/adb_parser.cpp
- adb_parser/adb_parser.h
- adb_parser/adb_xmlCreator.cpp
- adb_parser/adb_xml_parser.cpp
- adb_parser/adb_xml_parser.h
- adb_parser/buf_ops.cpp
- adb_parser/buf_ops.h
- common/tools_regex.h
- common/tools_regex_test.cpp
- mlxlink/modules/mlxlink_reg_parser.cpp
- mlxreg/mlxreg_lib/mlxreg_lib.cpp
- mlxreg/mlxreg_lib/mlxreg_lib.h
- mlxreg/mlxreg_lib/mlxreg_parser.cpp
- mlxreg/mlxreg_lib/mlxreg_parser.h
- mlxreg/mlxreg_ui.cpp
- mlxreg/mlxreg_ui.h
Description:
Tested OS:
Tested flows:
Issue: None
> port adb_parser to MFT 4.32

- mtcr_py/cmtcr.c
Add Python 3 C-API support in cmtcr.
> Add Python 3 C-API support in cmtcr

- mflash/mflash.c
Description: Until now, the number of sectors was limited to 64; therefore, only 3 of the BP bits were used. For backward compatibility (since there are flashes with only 3 BP bits), we continued reading 3 BP bits when displaying them during an HW query. However, due to new requirements that necessitate using all 4 BP bits for some flashes in certain configurations, we now determine the number of bits to read based on the flash, ensuring a safer read.
Tested devices: CX-6, CX-8
Tested flows: flint -d <dev> -ocr hw query
Issue: 4344800
Change-Id: I5fcc77fdc001a8fc95ca0700edac8f9e7936794e
> [BugFix][FlashWP] HW Query does not read whole 4 bits BP

- Makefile.am
- configure.ac
- mlxconfig/Makefile.am
- mlxconfig/mlxcfg_db_manager.cpp
- mlxconfig/mlxcfg_db_manager.h
- mlxconfig/mlxcfg_generic_commander.cpp
- mlxconfig/mlxcfg_generic_commander.h
- mlxconfig/mlxcfg_param.cpp
- mlxconfig/mlxcfg_param.h
- mlxconfig/mlxcfg_parser.cpp
- mlxconfig/mlxcfg_tlv.cpp
- mlxconfig/mlxcfg_tlv.h
- mlxconfig/mlxcfg_ui.cpp
- mlxconfig/mlxcfg_ui.h
- mlxconfig/mlxcfg_ui_tokens.cpp
- mlxconfig/mlxcfg_ui_tokens.h
- mlxfwops/lib/fw_version.cpp
- mlxfwops/lib/fw_version.h
- mlxtokengenerator/Makefile.am
- mlxtokengenerator/mlxtkngenerator.cpp
- mlxtokengenerator/mlxtkngenerator.h
- mlxtokengenerator/mlxtkngenerator_utils.cpp
- mlxtokengenerator/mlxtkngenerator_utils.h
- mlxtokengenerator/mlxtoken.cpp
- mlxtokengenerator/mlxtoken.h
Description:
1) msttokengenerator tool
2) get challenge command in mstconfig
3) token query/end commands in mstconfig
4) mstconfig commander alignment
> [mlxtokengenerator] porting token capabilities to mstflint

- flint/subcommands.cpp
- flint/subcommands.h
- mlxfwops/lib/fs_pldm.cpp
- mlxfwops/lib/fs_pldm.h
- mlxfwupdate/mlnx_dev.cpp
- pldmlib/pldm_dev_id_record.cpp
- pldmlib/pldm_pkg.cpp
PLDM - add commits that were not ported for April release
> PLDM - add commits that were not ported for April release

- mstflint.spec.in
fix for [MSTFLINT] Bug SW [#4506395]: [Master_Devel][GB200][RPM][Tarball] Enable Fw Manager Causes Build Issue 
Issue:4506395
> fix for [MSTFLINT] Bug SW [#4506395]: [Master_Devel][GB200][RPM][Tarball] Enable Fw Manager Causes Build Issue 

- mstflint.spec.in
fix for [MSTFLINT] Bug SW #4506395: [Master_Devel][GB200][RPM][Tarball] Enable Fw Manager Causes Build Issue
Issue:4506395
> fix for [MSTFLINT] Bug SW #4506395: [Master_Devel][GB200][RPM][Tarball] Enable Fw Manager Causes Build Issue

- mlxlink/modules/mlxlink_commander.cpp
> bug fix | add initialization for the xdrslowActive parameter

- common/mcam_capabilities.cpp
- ext_libs/muparser/t_ParserTest.cpp
- mlx5ctl/mlx5ctlu.c
- mlxdpa/dpa_elf/dpa_elf.h
- mtcr_ul/mtcr_common.c
- nvml_lib/nvml_c_wrapper.cpp
- nvml_lib/nvml_device.cpp
- nvml_lib/nvml_lib_wrapper.cpp
- pldmlib/pldm_utils.cpp
- pldmlib/pldm_utils.h
- small_utils/mstfwctrl.c
added missing license
Issue:4517958
> added missing license

- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/printutil/mlxlink_record.cpp
- mlxlink/modules/printutil/mlxlink_record.h
Description:
Tested OS:
Tested flows:
Issue:4543604
> mlxlink | bug fix for help menu is missing some flags.

- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_commander.cpp
Description:
Tested OS:
Tested flows:
Issue:
> mlxlink | adding support for tx_bias_lane scaling factor.

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
1- SNR values are N/A
2- CDR LOL and other module fields print values for wrong lanes when ports are splitted 
3- power values convert from UW to DBM instead of reading with DBM
> 3 bug fixes:
