Mellanox/mstflint

- configure.ac
Description: add --enable-all-static flag
Issue:1703934
Add a new flag to configure:
--enable-all-static for enabling creation of non dynamic executables for mstflint:
Typical usage:
./autogen
./configure --disable-dc --disable-openssl --disable-shared --disable-inband --enable-static-libstdcpp --enable-all-static
make
> generate a statically linked binary of mstflint

- configure.ac
Desciption: Add CXX flags for enabling static libstdc++ when all-static
is enabled
Issue: 1703934
> Title: enforce static libstdc++ for all-static flag

- configure.ac
description:
mlxarchive cannot compile when openssl is disabled.
Issue: 1677172
On branch master_devel
> Title: build mstflint fail with --disable-openssl

- common/python_wrapper.sh
1734769: Python tools don't work on FreeBSD 13
> issue: 1734769: Python tools don't work on FreeBSD 13

- configure.ac
- pldmlib/pldm_buff.cpp
Description: fix warning with pldm_buff, Fix compile when lib exists but
no header of iniparser
issue:1768198
issue:1767646
> Title: fix compile of mlxfwmgr

- mlxlink/Makefile.am
- mlxlink/modules/Makefile.am
- mlxlink/modules/printutil/Makefile.am
Description: Changed to force static as it's done in all of the other tools and removed declaration of mstlink as a script in addition to program.
Issue: 1771510.
Signed-off-by: Dan Goldberg <dang@mellanox.com>
> Title: Fixed multiple issues in mstlink Makefiles.

- mlxfwupdate/Makefile.am
Description: Add mtcr_ul library from mstflint explicitly
Issue:1768555
> Title: Fix linkage of mtcr_ul when there is a conflict with ofed

- configure.ac
- mlxlink/Makefile.am
- mlxreg/Makefile.am
Description: There is no need for this dependency and for the coupling between openssl and adb generic tools.
Issue: 1788615.
Signed-off-by: Dan Goldberg <dang@mellanox.com>
> Title: Removed openssl dependency from adb generic tools.

- kernel/mst_main.c
Description: Adding a capability to show all physical function of the devices.
Issue: 1797470
> mstflint doesn't recognize second port on dual port devices

- mlxarchive/mlxarchive.cpp
Description: mstarchive will treat a new file as a file and not a
directory
Issue: 1898265
> Fix - When mstarchive was given a path to a new file it recognized it as a directory.

- mstflint.spec.in
This PR includes three fixes discussed previously in email. For "spec: Add missing dependencies for ADB generic tools" we do not enable building the ADB generic tools but do conditionally include the dependencies required when building those tools (e.g., mstlink, mstreg) is enabled.
> Spec file fixes

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_logger.cpp
Description: mlxlink catch exception and fprintf syntax errors on different platforms fixed.
Issue: 1909668
> Fix - build with --enable-adb-generic-tools failed on Ubuntu, Fedora and RH

- mtcr_freebsd/mtcr_ul.c
Description: Update mtcr_ul.c for freeBSD to use new field in mfile
struct.
Issue: 1912211
> Fix - Build failed on freeBSD after mfile struct changed.

- mstflint.spec.in
Description: Temporary disabling expat-devel library dependency to preserve compatibility with SLES OS which holds a different name for exapt-devel, which is libexpat-devel.
Issue: 1916746
> Temporary disabling expat-devel library dependency

- mstflint.spec.in
Description: Some packages have different names in SLES and RH.
A variable for lib name was added to support both distros.
Issue: 1916746
> Added conditional lib name of the dependencies for cross-distro support

- mstflint.spec.in
Description: Temporary disabling boost_filesystem and boost_regex libraries dependency to
preserve compatibility with SLES OS which holds a different name for
those packages.
Issue: 1916746
> Temporary disabling boost_filesystem and boost_regex libraries dependency

- flint/subcommands.cpp
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
Description: It was added commented out and shouldn't be part of the code.
Both function and commented out usage were deleted now.
Issue: 1913895.
> Removed unused livefish check in flint subcommands

- resourcedump/mstresourcedump.py
Description: vhcaid flag will not be a part of the usage and help msg.
Issue: 1977689
> resourcedump – set vhcaid flag as hidden.

- mlxlink/modules/mlxlink_commander.cpp
[mstlink] Showing and setting external phy options are not supported for IB switches
Issue: 1930350
> Fixing external phy error message

- flint/Makefile.am
Description: Adding lzma lib to flint Makefile.am when "enable-fw-mgr"
flag is set.
Issue: 2037210
> Fix compilation issue when using "enable-fw-mgr" flag at configure step

- mstflint.spec.in
Description: when default python version on machine is python2 rpmbuild
fails since mstresourcedump uses python3 synatx which is incompatible with python2.
Now specfile ignore these python syntax errors related to mstresourcedump tool.
Issue: 2035716
> Removing python byte compilation from specfile

- mlxconfig/mstprivhost.py
Description: Better error message when trying to run restrict command
from host instead of ARM.
Issue: 2048097
> Fix error message when running restrict commands from host

- resourcedump/mstresourcedump.py
Description: set the argparse to allow more than 80 characters per line at the version command.
Issue: 1930381
> Fix 1930381- [resourcedump] version should be one line only.

- small_utils/mcra.c
Description: When given address is larger than max value of unsigned
int, relevant error is displayed and exit.
Issue: 1716152
> Fix mcra address parsing

- dev_mgt/tools_dev_types.c
Description: hw_dev_id wasn't assigned in case of linkx device, now
fixed.
Issue: 2080311
> Fix - dm_get_device_id() return wrong hw_dev_id in case of linkx device

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/printutil/mlxlink_cmd_print.cpp
- mlxlink/modules/printutil/mlxlink_record.cpp
- mlxlink/modules/printutil/mlxlink_record.h
Fixes and Changes:
- Adding support to use PAM4 RX/TX rates(50G_1X, 100G_2X) in PRBS mode
- Adding support to work with PAM4/NRZ speeds for new devices
- Fixing JSON format issues
- Updating PAOS failed message
- Fixing ambiguous else if statements
- Fixing split issues for Spectrum switch
- Updating some of the help messages
- Validating the Firmware version while working on PCIe port
- Adding support to access the PCIe port by "--port" flag
- Adding RX and TX modulation for HDR speeds
- Fixing lane width for 50G PAM4 speed
> [mstlink] Adding some fixes and updates

- mtcr_py/mtcr.py
Need to check if the pointer is 64bit or 32 bit before loading the dll's.
Issue: 2083458
> Segmentation fault and access violation when dealing with cables on python tools

- small_utils/mlxfwresetlib/cmd_reg_mfrl.py
- small_utils/mlxfwresetlib/mlxfwreset_mlnxdriver.py
- small_utils/mstfwreset.py
1. Add a check for reset-level and reset-type 
2. bluefield on PPC - remove DMA controller (NVME emulation) from list
3. wait 1 sec if wait_for_fw_ready gets exception
Issue:2098635
> mstfwreset bug fixes (2074458; 2053621; 1980064)

- mlxfwupdate/mlxfwmanager.cpp
Description: When using flags:
--image-dir <empty directory> --list-content
and no images found, now we return RC = 9
which means "ERR_CODE_IMG_NOT_FOUND"
Issue: 2076751
> [mstfwmanager] Fix RC when no images found

- adb_parser/adb_parser.cpp
Description: In older versions of boost library (1.41) is_relative isn't
implemented therefore we need to keep our implementation.
In addition license is fixed.
Issue: 2107652
> Fix RH6.3 compliation issue when no is_relative function in boost

- adb_parser/adb_parser.cpp
> Fix RH6.3 compilation issue when string() isn't implemented for boost::filesystem::path

- mlxlink/modules/mlxlink_ui.cpp
On Oracle Linux 8, mstlink is built with the hardening flag,
-D_GLIBCXX_ASSERTIONS":
$ rpm --eval %__global_compiler_flags
-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2
-Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong
-grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1
When run, the command cores:
$ mstlink -d 13:00.1
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference
std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type)
[with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>;
std::vector<_Tp, _Alloc>::reference = unsigned int&; std::vector<_Tp,
_Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n <
this->size(), …
> Fix mstlink core dump

- mlxlink/modules/mlxlink_ui.cpp
Description: This fix wasn't tested as part of mstflint-4.14.0-1
release, therefore it was temporarily removed and now restored.
Issue: PR #302
> Restoring markhaywood #302 PR code changes after mstflint-4.14.0-1 release

- resourceparse/parsers/AdbParser.py
Description: should be as [0] if high_bound="VARIABLE".
Issue: 2143482
> resourceparse - add support for unlimited arrays

- kernel/mst.h
- mtcr_ul/mtcr_ul_com.c
Description:
The bug is a combination of two issues:
1. Wrong calculation buffer offset in mtcr_ul.
2. Wrong ioctl implementation in mstflint driver.
Issue: 2172506
> mlxdump reads corrupted values when mstflint driver is loaded due to bugs in mtcr module.

- flint/subcommands.cpp
Description:
Removed redundant snprintf into a char array.
Issue: 2170787
> Fixed format-security warning in flint's checFwVersion

- configure.ac
This reverts commit c293dbae9fe84183af186787acaac199cb1279d9.
The reverted change is still part of master_devel and will be merged to master once it's stable.
> Revert "Allow to override build date with SOURCE_DATE_EPOCH"

- configure.ac
Description: unclosed double-quote string caused error during running configure under FreeBSD
Issue: 2231988
> Fixed bug in the configure script

- flint/subcommands.cpp
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
Description: the --key_uuid flag with export_public_key shouldn't accept
non-hex values
Issue: 2277680, 2277641, 2277715
> mstflint fix - export_public_key command accepts any PEM file with any size

- flint/subcommands.cpp
> mstflint fix - the --key_uuid flag with export_public_key shouldn't accept non-hex values

- mstflint.spec.in
When "optflags" are defined in the spec file they override the flags set
by GNU Autotools and the platform's default RPM macros during rpmbuild.
On RHEL8 or OL8 this causes the rpmbuild of mstflint to fail during
cross compile checking during the "configure" phase.
On RHEL7 or OL7 this results in mstflint compiling and linking with
a different set of options than what the platform RPM macros should be
setting.
Signed-off-by: Aron Silverton <aron.silverton@oracle.com>
> spec: Do not set "optflags"

- mtcr_ul/mtcr_ul_com.c
Fixed: 2411879: mstflint tools causing to core dump when providing wrong pci device
> Fixed several buffer overflow bugs:

- mlxlink/modules/mlxlink_cables_commander.cpp
GCC complains that the format string "dword[%d]" will not into 16 bites.
Increase that size a bit.
> increase fiedName size to fix #391

- common/compatibility.h
- mtcr_ul/packets_common.h
- tools_layouts/adb_to_c_utils.h
Add support for three more architectures: two 32bit ones (hpa and m68k) and a newer 64 bit one (riscv64).
> Extra architectures

- include/mtcr_ul/mtcr.h
- mtcr_ul/mtcr_ul_com.c
Portable applications should employ sysconf(_SC_PAGESIZE) instead of getpagesize().
> getpagesize (get memory page size) is deprecated.

- mlxlink/modules/mlxlink_err_inj_commander.h
Description:
Fixed as part of transition to clang in FreeBSD.
Issue: 2670735
> Removed unused class members in mstlink

- kernel/mst_main.c
Remove the HAVE_UNLOCKED_IOCTL and HAVE_COMPAT_IOCTL aren't supported anymore and we don't have 32-bit tools in a 64-bit kernel.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4e24566a134ea167441a1ffa3d439a27cf400880
> Remove the HAVE_UNLOCKED_IOCTL and HAVE_COMPAT_IOCTL

- configure.ac
(curl/curl.h is not found while it exists in /usr/local/include/)
> Fixed FreeBSD build error when --enable-adb-generic-tools is used

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/printutil/mlxlink_record.h
Description:
Adding new flag (amber_collect) for 16 and 7 nm devices.
This flag will be used instead of (ber_collect) for these devices
Issue: 2633033
> [mstlink][NDR_GEN] Supporting amBER collection for 16/7nm devices

- mlxconfig/mlxcfg_parser.cpp
- mlxconfig/mlxcfg_ui.cpp
Description:
remove the name qualifier in mlxconfig, when using the enum "device_type"
Tested OS: ppc64
Tested devices: None
Tested flows:
git clone ...
git checkout master_devel
autogen.sh
configure
make
Issue: 2848241
> fix compilation error when using old GNU Make versions (V3.82).

- adb_parser/adb_db.cpp
- adb_parser/adb_parser.cpp
- adb_parser/adb_parser.h
- mlxlink/modules/mlxlink_commander.cpp
- mlxreg/mlxreg_lib.cpp
Description:
fixed compilation errors related to --enable-adb-generic-tools configuration
Tested OS: ppc64 RH7 , Linux64 RH8
Tested devices:None
Tested flows:
clone mstflint from github
git checkout master_devel
./autogen.sh
./configure --enable-adb-generic-tools
make
Issue:2839525
> fix compilation errors which came from PR#454 (4.18 alignment)

- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_cables_commander.h
Description:
mlxlink cable voltage incorrect, divide by 10 error
Tested OS: Centos7.9, Ubuntu 20.04
Tested devices: CX5, CX6DX
Issue: 2845430
> [Huwei]MFT mlxlink cable ddm print bug - also in mstflint

- mtcr_py/mtcr.py
Description:
during cleanup in mtcr we removed 2 unimplemented functions, a call to those functions was left out and caused that error.
Issue: 2849868
> fix undefined symbol error in mstfwtrace

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
Fixing amber_collect for Quantum switch while split ready
Tested devices: Quantum
Tested flows: mstlink amber collector
Issue: 2850001
> [mstlink] Fixing amber_collect for Quantum while split ready

- dev_mgt/tools_dev_types.c
- dev_mgt/tools_dev_types.h
to avoid unwanted error prints in mst status
> [dev_mgt] added a non-print version of dm_get_dev_id func

- configure.ac
Description:
the fips module is not actually required and is not part of the minimal version check.
removed the mention of fips module from the massage
Issue: 2872291
> [mstflint] print not required error message when openssl version not supported

- mlxfwupdate/mlxfwmanager.cpp
Description:
The parser was looking for a number followed by a whitespace.
in some OS giving just a number would count as pass but in the case of WINPE (and also windows arm)
not getting the full parse raised the error flag.
code was updated to expect a number only. (trailing whitespace are still acceptable based on testing)
Tested OS: linux (apps-104), windows ARM(winqa-arm-014)
Tested devices:None
Tested flows:
run the command "mlxfwmanager --download C:\tmp" with the following outputs:
3 - pass
a - invalid
3a - invalid
a3 - invalid
3 - pass
3   - invalid
Issue: 2883937
Change-Id: I4e8a4552abe8a0b3e42575f6ec12d372f93bb2f3
Signed-off-by: Tomer Tubi <ttubi@nvidia.com>
> fail downaload files from mellanox server

- mlxfwops/lib/fs4_ops.cpp
Description: In case of minimized image we don't have MAIN section, so
we need to skip RemoveCRCsFromMainSection
Tested OS: N/A
Tested flows: N/A
Issue: 2928610
Change-Id: I5033eb48ea9ce0b0e8c6fd24f586320ddbf0c02e
Signed-off-by: Matan Eliyahu <matanel@nvidia.com>
> Skip MAIN CRCs removal in case MAIN doesn't exist for fw update sign flow

- mflash/mflash.c
- mlxfwops/lib/fs4_ops.cpp
- mlxfwops/lib/fw_ops.h
1. Fix burning progress percentage
2. Remove false warning message for Quantum2 and CX7
> burn-tools 2 bug fixes related to encrypted image burning

- tracers/fwtrace/mstfwtrace.py
script should run from python wrapper which decide on what python version to run
> remove shebang line from mstfwtrace.py

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
Description:
PRM change the fields accessto array, so tool changed according that
Tested devices: SPC2, SPC3
Tested flows: mlxlink commands
Issue: 2917956
Issue: 2937749
> Fixing PMLP field access according to the PRM

- tracers/fwtrace/mstfwtrace.py
Description:
add check for FW info to prevent run and fail on livefish mode.
match the output to internal mft tracer tool.
Tested OS:Linux
Tested devices: Nic in Livefish mode ( apps-01 -d 07:00.0)
Tested flows:
run "mstfwtrace -d 07:00.0 --tracer_mode MEM -m ICMD -l 1 -i all -s" from issue and expect output:
"-E- Failed to get FW INFO: Unsupported icmd version, device maybe in livefish mode."
Issue:2969662
> [mstfwtrace] livefish mode message

- resourcedump/fetchers/ResourceDumpFetcher.py
Description:
Set code to support python 3.4
Tested flows:
Issue: 2950008
> [resourcedump] error while running with old python 3

- resourcedump/fetchers/ResourceDumpFetcher.py
Description:
Adding a different error message for the 'pyverbs not installed' case.
Adding a different error message for any error the 'pyverbs' throws.
Tested flows: modified the command sent to the resourcedump to verify the new changes by causing the relevant errors.
Issue: 3007076
> [resourcedump] adding additional error messages for the mem flag

- resourceparse/parsers/AdbParser.py
Description:
Tested devices: NA
Tested flows: changed offset/size fields in a rp tracked node in .adb file to all valid forms and ran the tool
Issue: 2937456
Change-Id: I4191b5050d10da4614bbe4b38743ab8d24ea57a3
Signed-off-by: Alon Strutsovsky <astrutsovsky@nvidia.com>
> fix offset/size adb fields parsing

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing invalid fec error message
Tested devices: ConnectX-6
Tested flows: mlxlink fec configuration
Issue: 2920878
> [mstlink] Fixing invalid fec error message

- mstdump/crd_main/mstdump.c
Description:
The 'full' flag default value was changed from false to true,
causing the tool to print out the sp2 addresses as well.
Tested devices: ConnectX5
Tested flows:
Issue: 2979319
> [mstregdump] changing the default value of the full flag to true

- mstdump/crd_lib/crdump.c
- mstdump/crd_main/mstdump.c
Description:
sp2 addresses are not marked as enabled
Tested devices: CX6
Tested flows: dump and check that contains the expected address list
Issue: 2979319
Change-Id: I8dbf4176fc69fa899021f42a62fc846830112d30
> bugfix, mstdump_pld doesn't dump sp2, where mlxdump mstdump do

- fw_comps_mgr/fw_comps_mgr.cpp
This reverts commit 97e3f2241f43062da122e604b2a035a2c2e1f646.
> Revert "Since CX7 IB has issues with sending MAD for mgir.fw_info using mad_ifc_general_info_fw() we send regular MGIR"

- small_utils/mlxfwresetlib/mlnx_peripheral_components.py
- small_utils/mlxfwresetlib/mlxfwreset_mlnxdriver.py
- small_utils/mstfwreset.py
1. In case of socket-direct devices we need to wait
for both PCI devices after the PCI link toggle
2. On Windows OS, where there are no network drivers installed
the tool should assume that there is no management (Rshim)
driver
> [mlxfwreset] bug fixes

- resourcedump/fetchers/ResourceDumpFetcher.py
Description:
mem arg did not reach inner fetch function in the case of reference seek
Tested devices: CX6LX
Tested flows: run mstdump with segment 1011 and depth==1
Issue: 3033347
Change-Id: Ib02f3971c55d288e2e7eea89f21c97d43040c765
Signed-off-by: Alon Strutsovsky <astrutsovsky@nvidia.com>
> depth>0 fails

- debian/mstflint.links
Signed-off-by: Tzafrir Cohen <nvidia@cohens.org.il>
> Symlink libmtcr_ul headers into the includedir

- mlxconfig/Makefile.am
to support regex on c++11 machines
> fix mlxconfig makefile to include boost when builder in order 

- kernel/mst_main.c
Description:
Missing device IDs caused a failure to work with
those devices in secure boot.
In this mode the communication must go only through
the signed LKM but this LKM doesn't recognise the missing
devices and refuses to work with them.
> Added missing device IDs to mstflint kernel module

- mlxsign_lib/mlxsign_lib.h
- mlxsign_lib/mlxsign_signer_interface.h
Description: include was moved to the proper file, avoiding indirect ssl header include
Tested flows: build
Issue: 3108992
> mstflint build issue when using --disable-openssl

- mlxconfig/mlxcfg_db_manager.cpp
- mlxconfig/mlxcfg_db_manager.h
- mlxconfig/mlxcfg_tlv.cpp
Description:
mlxconfig - changing regex use to strstr.
Tested devices:CX6
Tested flows:
mlxconfig -d {device} q
mlxconfig -d {device} s LINK_TYPE_P1=2
mlxconfig -d {device} q LINK_TYPE_P1
check that it was changed
mlxconfig -d {device} i
check that physical ports look ok
Issue:3114968
> [mlxconfig] - changing regex to strstr.

- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_cables_commander.h
Description:
-> Fixing negative arguments check
-> Fixing rx amplitude configuration
-> More validation over arguments
Issue: 3067085
Issue: 3042144
Issue: 3038403
Issue: 3066878
> [mstlink] Fixing cable control params issues

- mlxconfig/mlxcfg_generic_commander.cpp
- mlxconfig/mlxcfg_parser.cpp
Description: Removed unused variables in mlxconfig for building with "NO_OPEN_SSL" flag
Tested flows: Build
Issue: 3115231
> [MSTFLINT] mstflint build unused variables

- resourceparse/parsers/AdbParser.py
- resourceparse/parsers/Parser.py
- resourceparse/utils/constants.py
[resourceparse] adding support for union selectors
Description:
for US nodes, show only the selected field
Tested flows:
Issue: 3127046
> [resourceparse] adding support for union selectors

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_enums.h
- mlxlink/modules/mlxlink_err_inj_commander.cpp
- mlxlink/modules/mlxlink_err_inj_commander.h
- mlxlink/modules/mlxlink_maps.cpp
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_user_input.cpp
- mlxlink/modules/mlxlink_user_input.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
Adding support for PCIe error injection feature for ConnectX-7
The following flags were added to the tool:
--pcie_error_injection
--error_type
--erro_injection
--injection_delay
--dbdf
--error_parameters
Issue: 3198240
> [mstlink] PCIE Error Injection

- flint/subcommands.h
- mlxsign_lib/mlxsign_signer_interface.h
Tested flows: ./autogen.sh && ./configure --disable-openssl && make -j16
Issue: 3213043
> Fix compilation when openssl lib is missing (with configure flag --disable-openssl)

- mlxlink/modules/mlxlink_ui.cpp
Description:
Adding missing loopback configuration to the help menu (LL loopback)
Issue: 3147128
> [mstlink] Fixing missing loopback configuration in the help menu

- mlxlink/modules/mlxlink_commander.cpp
Description:
PCIe Gen2 servers does not support eye information
Issue: 3142236
> [mstlink][PCIE] Gen2 servers does not support eye info

- mft_utils/calc_hw_crc.c
It is not necessary to create a copy of the input array just to invert the first two bytes. We can invert these bytes on the fly during the crc calculation. This way a memory allocation is avoided and we do not need to worry about malloc failing.
> Eliminate memory allocation in calc_hw_crc

- mlxlink/modules/mlxlink_maps.cpp
Parameter 2 is valid for UNEXPECTED_CPL error type:
Bit 16: 0 – use default completion size (1).
1 – Use completion data size from bits 15:0
Bits 15:0: Completion size in bytes.
Issue: 3233196
> [mlxlink][PCIE Err Inj] Un-restricting param 2 for UNEXPECTED_CPL error

- mlxlink/modules/mlxlink_commander.cpp
Description:
Removing 50G speed from the warning message while configuring RM loopback for ConnectX6 and ConnectX6-DX devices.
Issue: 3272703
Hash: ee8c8d7a
> [mstlink][Remote loopback] Removing 50G speed from the warning message

- mlxlink/modules/mlxlink_commander.cpp
Description:
While running on test mode, the histogram information is not relevant.
Issue: 3229949
> [mstlink] Fixing error missing while getting histogram info on test mode

- mstdump/crd_main/mstdump.c
Description:
Tested OS:
Tested flows:
Issue: 3338471
> [mstregdump] - bugfix seg-fault due to null instead empty string

- small_utils/congestion.cpp
Description:
It return uint32 and not uint8
Issue: 3343667
> Fixed MCAM array size

- flint/subcommands.cpp
- mlxfwops/lib/fs3_ops.cpp
- mlxfwops/lib/fs3_ops.h
- mlxfwops/lib/fs4_ops.cpp
- mlxfwops/lib/fs4_ops.h
- mlxfwops/lib/fw_ops.cpp
Description:
1. Enabling write block ('wb') command for FW images
2. Fixing 'verify showitoc' to display entries content as expected
Tested flows: mstflint -i <bin> wb <bin> <addr>
mstflint -i <encrypted_bin> v showitoc
Issue: 3348079
> [flint][mlxfwops] Enable wb command on binary FW image + encrypted verify showitoc bug fix

- configure.ac
- mtcr_ul/Makefile.am
- mtcr_ul/mlx5_ifc_stub.h
- mtcr_ul/mlx5ctl.h
We are using several structure definitions from Linux kernel header files in this user space code. Those are:
struct mlx5_ifc_access_register_out_bits
struct mlx5_ifc_access_register_in_bits
from ./include/linux/mlx5/mlx5_ifc.h
While this violates the typical assumption that kernel headers should not be used in user space code, we have determined that these specific structures have not been modified for years and are unlikely to be modified in the future.
As a result, we have decided to replicate the necessary definitions directly in our codebase rather than include the kernel headers. This approach should help us avoid potential issues that could arise from including kernel headers in user space code.
> mtcr_ul: eliminate dependency in Linux kernel headers

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_amBER_collector.h
- mlxlink/modules/mlxlink_enums.h
Description:
-> Module_status_4:
Changed IB lanes (column D) index to 4x.
-> Link_status_3:
Added a new field from the PPCNT.Physical_Layer_Counters: successful_recovery_events
-> Removed all SLRG readings for 7nm devices
Issue: 3408638
> [mstlink] Updating to amber 2.13

- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_utils.cpp
Description:
Changing SLTP default params for Spectrum-4 if the port is down to use the NDR serdes params
Issue: 3430786
> [mstlink] Changing SLTP default params for Spectrum-4

- mlxlink/modules/mlxlink_commander.cpp
Description:
Adding square_Wave30 to the error message
Issue: 3408416
Issue: 3410109
> [mstlink] Fixing missing RX PRBS in the error message

- kernel/mst_main.c
UBSAN is catching an illegal shift in mst_release() and is reporting it to syslog.  The problem is that mst_release() is doing:
slot_mask = ~(1 << (md->connectx_wa_slot_p1 - 1));
but md->connectx_wa_slot_pl is only set if the user calls the undocumented PCI_CONNECX_WA ioctl().  When the file is opened connectx_wa_slot_pl is set to 0.  If a user simply does an open() and then a close() then md->connectx_wa_slot_p1 is 0 and mst_release will try to do a shift by -1.
> Fix illegal shift in mst_release

- mflash/mflash_gw.c
- mflash/mflash_new_gw.c
- reg_access/reg_access.c
Avoid implicit declarations of cibfw_register_mfai_pack, cibfw_register_mfai_unpack, cibfw_register_mfai_size by including <tools_layouts/cibfw_layouts.h>, and of getenv by including <stdlib.h>.
(cherry picked from commit 3d033115fd0937b675b75f5d1fc12dc015efcf07)
Signed-off-by: Alex Blago <alexbl@nvidia.com>
> Add additional #include directives for C99 compatibility

- small_utils/mstfwreset.py
Description: N/A
Tested devices: BF2, CX6
Tested flows: mlxfwreset reset/query
Issue: 3459379
Change-Id: Ic5a958519d2926e850cf8a5df0dbf5ce2ac11900
> Remove mlxfwreset support for BF2/BF3

- dev_mgt/tools_dev_types.c
- include/mtcr_ul/mlx5ctl_ioctl.h
- include/mtcr_ul/mtcr_mf.h
- mtcr_ul/mlx5ctl.c
- mtcr_ul/mtcr_ul_com.c
The purpose of this commit is to modify the mstflint tools to work with the latest upstream kernel (mlx5ctl). This driver will be added in the upcoming 6.7 version of the upstream kernel.
This patch modifies the device ID retrieval method to ensure smooth operation without needing VSEC access, instead relying solely on PRM access.
> mtcr_ul: Adapt tools to the upstream kernel

- small_utils/mlxfwresetlib/cmd_reg_mfrl.py
- small_utils/mlxfwresetlib/mlnx_peripheral_components.py
- small_utils/mlxfwresetlib/pci_device.py
- small_utils/mstfwreset.py
Bluefield:
The responsibility of resetting the Bluefield it will be handled by the Nic driver. The duration of the reset time is retrieved from the DTOR register.
Cedar:
The responsibility of resetting all Cedar devices when the user requests it will be handled by mlxfwreset tool. The user needs to provide one of the Cedar devices to the tool and the tool will then proceed to reset all the devices accordingly. As the final step in the reset process, a reboot command will be executed, resulting in the rebooting of the entire setup.
> The mlxfwreset tool supports resetting the Cedar and Bluefield devices

- reg_access/regaccess.py
Description:
Removed some referances to registers we don't use in mstflint.
Tested devices:cx5
Tested flows:
mstfwreset -d 86:00.0 -y r
Issue:3550491
> [regaccess.py] bug fix for mstfwreset crush on Linux

- mlxreg/mlxreg_lib/mlxreg_lib.cpp
Description:
Tested OS:
Tested flows:
Issue: 3557887
> [mtcr] NULL->false compilation fix for freebsd

- dev_mgt/Makefile.am
- mtcr_py/Makefile.am
- reg_access/Makefile.am
Files registered in both xxx_DATA and dist_xxx_DATA get installed twice which may cause error when building with make -j
> fix race condition during install

- mflash/mflash_dev_capability.c
Fix the following failure:
mflash_dev_capability.c:43:1: note: 'getenv' is defined in header '<stdlib.h>';
did you forget to '#include <stdlib.h>'?
42 | #include "mflash_dev_capability.h"
+++ |+#include <stdlib.h>
43 |
> mflash: Fix build failure

- common/compatibility.h
- mtcr_ul/packets_common.h
- tools_layouts/adb_to_c_utils.h
Adding support for little endian loongarch64 running linux.
The following features have been tested to work on a real loongson 3c5000 with a connectx-3:
- mstconfig querying settings values
- mstconfig setting sriov / port modes
- mstflint querying firmware version
> hardware support: linux on loongarch64

- common/compatibility.h
- mtcr_ul/packets_common.h
- tools_layouts/adb_to_c_utils.h
Add new architecture e2k. Patch has been tested on linux e2k. For full support, please update two files:
config/config.guess
config/config.sub
from official resource: https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html
> Add new architecture e2k

- kernel/mst_main.c
fix build of mstflint_access on recent kernels (>= 6.4)
> Fix build of mstflint_access on recent kernels (>= 6.4)

- reg_access/reg_access.c
mstfwreset -d 03:00.0 -y r
-E- /usr/local/lib/mstflint/python_tools/rreg_access.so: undefined symbol: reg_access_nic_cap_ext.
Description:
Added missing implementation of the functions in .c file
> fix for undefined symbol

- kernel/mst_main.c
I got the comparison order somehow messed up in my last PR.
> kernel module: fix wrong comparison order

- configure.ac
When cross-compiling (e.g. from x86-64 to ARM64), the test binary used here for std::regex functionality testing does not work. It gets either compiled for the host architecture which means nothing, does not compile at all or is not executable on the host architecture in most cases, when compiled for ARM64.
> fix cross-compilation check for boost::regex

- mlxlink/modules/mlxlink_commander.cpp
Description:
Fixing NDR modulation config in prbs testmode
Tested devices: QTM-2
Tested flows: mlxlink prbs test_mode
Issue: 3612477
> [mlxlink] Fixing NDR modulation config in prbs testmode

- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_reg_parser.cpp
- mlxlink/modules/mlxlink_reg_parser.h
- mlxlink/modules/mlxlink_user_input.cpp
- mlxlink/modules/mlxlink_user_input.h
Description:
Adding new flag (--plane) to the internal tool for plane view The default view will be aggregate view
If the plane is provided then the tool will set plane_ind field for all access reg requests
Tested devices: NA
Tested flows: mlxlink --plane X
Issue: 3566234
> [mlxlink] [Patch-2] Adding support for plane

- mlxlink/modules/mlxlink_commander.cpp
Description:
mlxlink failed with '-E- Showing PDDR raised the following exception: Failed to send access register: Bad parameter'
There is a problem that if the device doesn't support PDDR reg with select_page=3 the tool won't work, even though it dosn't need that info for all flags of mlxlink. Changing that the function will be called only for flags that need that informantion.
MSTFlint port needed: None
Tested OS: None
Tested devices: None
Tested flows: mlxlink -d {device}
Issue: 3649766
> [mlxlink] - mlxlink failed with '-E- Showing PDDR raised'

- mlxlink/modules/mlxlink_err_inj_commander.cpp
- mlxlink/modules/mlxlink_ui.cpp
Description:
Fixing error types in the help menu
Fixing erro message while providing invalid error parameter Adding missing info message while configuring FEC for main\tile ports
Tested devices: CX7, SPC-3
Tested flows:
mlxink full commands
Known gaps (with RM ticket):  NA
Issue: 3577410
Issue: 3541189
Issue: 3567074
> [mlxlink] Fixing error message and help menu issues

- reg_access/regaccess_hca_ext_structs.py
Description:
Due to unexported file to mstflint, some fields were missing.
Tested devices:cx6
Tested flows: mstfwreset  -d 82:00.0 -y r
Issue: 3757175
> [mstfwreset] bug fix for mgir doesn't return the correct uptime.

- mlx5ctl/Makefile
- mlx5ctl/ifcutil.h
- mlx5ctl/mlx5ctl.h
- mlx5ctl/mlx5ctlu.c
- mtcr_ul/mlx5ctl.c
- mtcr_ul/mtcr_ul_com.c
1. Adjusting the IOCTLs according to community requests.
2. Introducing a small tool to interact with the driver, retrieving device information. This tool will not be included in the mstflint makefile and will need to be compiled separately. Here's an example of its output:
[root@mlx5ctrl_setup mstflint]# sudo ./mlx5ctl/mlx5ctl mlx5_core.ctl.0 ctldev: /dev/mlx5ctl-mlx5_core.ctl.0
Parent dev: 0000:00:07.0
UCTX UID: 2
UCTX CAP: 0x7
DEV UCTX CAP: 0x7
USER CAP: 0x1d
Current PID: 59168 FD 3
> Updates to the mlx5ctrl upstream driver include:

- mtcr_ul/mtcr_ul_com.c
- mtcr_ul/mtcr_ul_com.h
- mtcr_ul/mtcr_ul_icmd_cif.c
Description: in icmd_send_command_com: MWRITE_BUF_ICMD changes the endiannes, so in case of any failure after it, we do not get to the call to MREAD_BUF_ICMD which fixes back the endiannes. added a variable indicating whether the endiannes should be changed back. so even in case of any failure, in the cleanup stage we will know if the endiannes needs to be changed back.
Tested flows: modified the return value from FW to be bad status, and single stepped with the debugger to see we get into fix_endianness in the cleanup stage.
Issue: 3439259
> [mtcr] - fixed endiannes back in case icmd_send_command_com fails.

- mtcr_freebsd/mtcr_ul.c
Description: for FreeBSD, instead of including mtcr_ul_com.h, which should not be compiled as part of FreeBSD mtcr, include mtcr_freebsd/mtcr_ul.h.
Tested flows: compilation and mstflint -d <> q
Issue: 3849021
> fixed compilation issue in FreeBSD.

- flint/subcommands.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mlxfwops/lib/fs3_ops.cpp
- mlxfwops/lib/fs5_ops.cpp
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fsctrl_ops.h
- mlxfwops/lib/mlxfwops_com.h
- mlxfwupdate/mlnx_dev.cpp
- reg_access/reg_access.c
- reg_access/reg_access.h
[flint][XDR-switch/multi asic systems] - add sys_guid, node_guid, port_guid and allocated_guid to query command's output.
Description: when querying a device (asic) of type Quantum3(Sunbird) or ConnectX8, additional guids info will be displayed, letting the user learn more about the topography of the system. each GUID will be represented by 16 hexadecimal characters so it will be clear to the user that a GUID is 64 bits long.
Tested devices: emulation for Sunbird
Tested flows:
1. to check the info in PGUID reg used:
mlxreg -d   /dev/mst/mt4123_pciconf0  --reg_name PGUID --get --indexes "local_port=0,pnat=0,lp_msb=0,plane_ind=0"
2. ran flint -d <> q
3. made sure each GUID is represented by 16 hexadecimal characters which are the same as those seen when using mlxreg.
Known …
> [flint][XDR-switch/multi asic systems] - additional guids info for flint query.

- resourcetools/resourcedump_lib/src/sdk/Makefile.am
Description: added missing dependency library in makefile
Tested flows: dynamically load libresource_dump_sdk.so
Issue: 3760456
> resource_dump | fixed issue in shared object

- mlxlink/modules/mlxlink_commander.cpp
Description:
1. bug fix for missing field names when using PCIE flags.
2. bug fix for always taking ETH_FSM state.
Tested OS:
Tested flows:
Issue:3888149
> [mlxlink] several bug fixes

- mtcr_ul/mtcr_ib_ofed.c
This change addresses possible buffer overflow in mtcr_ul/mtcr_ib_ofed.c:
484  DWORD_TO_BYTES_BE(mad_data + IB_DATA_INDEX + CONFIG_ACCESS_MODE_2_BITMASK_OFFSET + (i * 4), &mask);
i: 0..13
IB_DATA_INDEX: 8
CONFIG_ACCESS_MODE_2_BITMASK_OFFSET: 8
mad_data capacity: 64
i=11: IB_DATA_INDEX+CONFIG_ACCESS_MODE_2_BITMASK_OFFSET+(i*4) = 60  - OK
i=12: IB_DATA_INDEX+CONFIG_ACCESS_MODE_2_BITMASK_OFFSET+(i*4) = 64  - out of mad_data !
i=13: IB_DATA_INDEX+CONFIG_ACCESS_MODE_2_BITMASK_OFFSET+(i*4) = 68  - out of mad_data !
569 DWORD_TO_BYTES_BE(vsmad_data + IB_DATA_INDEX + CONFIG_ACCESS_MODE_2_BITMASK_OFFSET + (i * 4), &mask);
i: 0..55
IB_DATA_INDEX: 8
CONFIG_ACCESS_MODE_2_BITMASK_OFFSET: 8
vsmad_data capacity: 232
i=53: IB_DATA_INDEX+CONFIG_ACCESS_MODE_2_BITMASK_OFFSET+(i*4) = 228 - OK
i=54: …
> mtcr_ul: Buffer overflow fixes

- dev_mgt/tools_dev_types.c
- include/mtcr_ul/mtcr.h
- mtcr_freebsd/Makefile.am
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
- mtcr_ul/mtcr_ul_com.h
- mtcr_ul/mtcr_ul_icmd_cif.c
ZombieFish mode is supported from ConnectX8(Gilboa), Quantum3(Sunbird), and onwards.
a device in Zombiefish mode resembles a device in Livefish mode as they are both non-functional. i.e. in recovery mode.
while a device in livefish mode identifies on PCI with its recovery device ID (hw device ID), a device in ZombieFish mode identifies with its functional device ID (sw device ID).
to determine whether a device is in ZombieFish mode, we read the global image status to see if it differs from System Enabled (0x0 for adapters and 0x5E for switches).
> add support to ZombieFish mode.

- mtcr_ul/mtcr_ul_icmd_cif.c
Description: livefish check was missing NULL check for mf & mf->dinfo.
Tested devices: Quantum IB
Tested flows: mstflint q
Issue: 3972524
> mstflint | segfault while sending ICMDs on IB device

- flint/subcommands.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/mlxfwops_com.h
Description: For alternate INI feature, expose
MGIR.FW_Info.ini_file_version in flint query
Tested OS: TBD
Tested devices: TBD
Tested flows: TBD
> [flint] Print new INI version field

- mlxfwops/lib/fs4_ops.cpp
Tested flows: flint query on qtm3 image
Issue: none
> [flint][fs5] adding missing dtoc header treatment

- mlxfwops/lib/fs5_ops.cpp
Description:
Tested flows: flint image verify
Issue: none
> [flint] fixed boot2 size endianess

- mflash/mflash.c
Description: added support for both gigaDevice and issi flashes with 512MB for connectX-8
Tested OS: n/a
Issue:3847244
> Support for new flashes for ConnectX-8 - commit fix

- include/mtcr_ul/mtcr_com_defs.h
- include/mtcr_ul/mtcr_mf.h
- kernel/mst.h
- kernel/mst_kernel.h
- kernel/mst_main.c
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
- mtcr_ul/mtcr_ul_com.h
- mtcr_ul/mtcr_ul_icmd_cif.c
- small_utils/mtserver.c
Description:
Late LF support: the driver will detect that the device is in Late LF mode to determine the right access method. LF in newer devices: in contrast to legacy LF, newer devices have VSC exposed. The driver will distinguish between a functional device and a LF device by the VSC type. When running MFT tools on a device in late LF mode, the user will get the same behavior received from a device in LF mode.
HLD - https://confluence.nvidia.com/pages/viewpage.action?pageId=3113761891
Tested OS: linux with driver loaded, linux user-level, FreeBSD
Tested devices: ConnectX8 (functional device and LF device)
Tested flows: see detailed test and outputs in the bottom of the HLD
Issue: 3909481 4043079
> [CX8, QTM3 and above] - add support for LF and Late LF mode

- include/mtcr_ul/mtcr_com_defs.h
- include/mtcr_ul/mtcr_mf.h
- kernel/mst.h
- kernel/mst_kernel.h
- kernel/mst_main.c
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
- mtcr_ul/mtcr_ul_com.h
- mtcr_ul/mtcr_ul_icmd_cif.c
- small_utils/mtserver.c
Description:
Late LF support: the driver will detect that the device is in Late LF mode to determine the right access method. LF in newer devices: in contrast to legacy LF, newer devices have VSC exposed. The driver will distinguish between a functional device and a LF device by the VSC type. When running MFT tools on a device in late LF mode, the user will get the same behavior received from a device in LF mode.
HLD - https://confluence.nvidia.com/pages/viewpage.action?pageId=3113761891
Tested devices: ConnectX8
Tested flows: see detailed test and outputs in the bottom of the HLD
Issue: 3909481 4043079
> [CX8, QTM3 and above] - add support for Late LF mode

- include/mtcr_ul/mtcr_com_defs.h
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
Description:
in case of failure in regular flow, change VSC space to the PCI space. HLD: https://confluence.nvidia.com/pages/viewpage.action?pageId=2924752605
Issue: 3533662
> support PCI and CORE VSC spaces separation

- include/mtcr_ul/mtcr_com_defs.h
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
Description:
in case of failure in regular flow, change VSC space to the PCI space. HLD: https://confluence.nvidia.com/pages/viewpage.action?pageId=2924752605
Issue: 3533662
> Description:

- mlxfwops/lib/fsctrl_ops.cpp
Description: In case of FW ctrl (MCC) flow, global image status is expected to be OK and we also don't print it as part of query (only in case of no FW ctrl flow). Removing the redundant code for reading global_image_status.
Tested devices: CX7
Tested flows: flint -d fwctrl2 q full; flint -d <DBDF> q full
Issue: 4086069
Change-Id: If0fab8de215e3da1fb2b75b6c01c1c73a11824d3
> [mlxfwops] Remove redundant code from fsctrl_ops.cpp

- configure.ac
- dev_mgt/dev_mgt.py
- dev_mgt/tools_dev_types.c
- dev_mgt/tools_dev_types.h
- include/mtcr_ul/mtcr_com_defs.h
- include/mtcr_ul/mtcr_mf.h
- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
- mlxreg/mlxreg_lib/mlxreg_lib.cpp
- mtcr_freebsd/Makefile.am
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_gpu.c
- mtcr_ul/mtcr_gpu.h
- mtcr_ul/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
- mtcr_ul/mtcr_ul_com.h
- mtcr_ul/mtcr_ul_icmd_cif.c
- tools_layouts/adb/prm/gpu/Makefile.am
- tools_layouts/adb/prm/gpu/ext/Makefile.am
- tools_layouts/adb/prm/gpu/ext/register_access_table.adb
- tools_layouts/prm_adb_db.cpp
- tools_layouts/prm_adb_db.h
- tools_res_mgmt/tools_res_mgmt.c
Description: adding support for PCI Bar0 GPU devices
1. adding PCI ID ranges discovery.
2. adding cr_space_offset + device endianness support.
3. routing mtcr_ul flows to use pci_cr device.
4. adding GPU external PRM support.
Tested devices: GB100
Tested flows: resourcedump, mstreg, mstlink
Issue: 3988451
> porting blackwell support to mstflint

- mlxconfig/mlxcfg_commander.h
- mlxconfig/mlxcfg_generic_commander.cpp
- mlxconfig/mlxcfg_parser.cpp
- mlxconfig/mlxcfg_ui.cpp
- mlxconfig/mlxcfg_utils.cpp
- reg_access/reg_access.c
- reg_access/reg_access.h
- tools_layouts/tools_open_layouts.c
- tools_layouts/tools_open_layouts.h
Description: There is an option to invalidate all TLVs. Now there is an option to reset a specific TLV using te reset command with a tlv as parameter.
> mlxconfig: Add support to invalidate single TLV

- kernel/mst_main.c
- mtcr_ul/mtcr_ul_com.c
fix for "[MSTFLINT] Bug SW #4143961: [mstflint kernel]: Failed to run mstflint tools over devices after load mstflint_access.ko module"
Description: The recovery space in VSC is supported only in ConnectX8, Quantum3, and above, so the get_space_support_status function should check whether it is supported after SS_ALL_SPACES_SUPPORTED is set; As this space is only for recovery, and SS_ALL_SPACES_SUPPORTED is relevant for functional devices.
Tested devices: ConnectX4
Tested flows:
insmod mstflint_access.ko
mstdlint -d 44:00.0 q
Issue:4143961
> fix for " Failed to run mstflint tools over devices after load mstflint_access.ko module"

- kernel/mst_main.c
- mtcr_ul/mtcr_ul_com.c
fix for "[MSTFLINT] Bug SW #4143961: [mstflint kernel]: Failed to run mstflint tools over devices after load mstflint_access.ko module"
Description: The recovery space in VSC is supported only in ConnectX8, Quantum3, and above, so the get_space_support_status function should check whether it is supported after SS_ALL_SPACES_SUPPORTED is set; As this space is only for recovery, and SS_ALL_SPACES_SUPPORTED is relevant for functional devices.
Tested devices: ConnectX4
Tested flows:
insmod mstflint_access.ko
mstdlint -d 44:00.0 q
Issue:4143961
> fix for "Failed to run mstflint tools over devices after load mstflint_access.ko module"

- mstflint.spec.in
successfully tested on Fedora 41.
> Allow RPM build on s390x architecture

- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/mlxfwops_com.h
- mtcr_ul/mtcr_ul_icmd_cif.c
fix for "Bug SW #4162297: [CX9] Flint Q Returns Image Type as FSCTRL"
Description: added missing cx9 device ID
MSTFlint port needed:yes
Tested OS: Ubunto20
Tested devices:cx9 emulation
Tested flows:flint q
Issue:4162297
> fix for "Bug SW #4162297: [CX9] Flint Q Returns Image Type as FSCTRL"

- include/mtcr_ul/mtcr_com_defs.h
Description: add CX9 support for pci-core VSC spaces separation
Issue: 4176631
> add CX9 support for pci-core VSC spaces separation

- mtcr_ul/mtcr_ib_ofed.c
Tested devices: QTM3
Tested flows: mstreg -d lid-0x0053,mlx5_0,  --get --reg_name MGIR
Issue: 4200388
> [mtcr_ul] disabled use of smp semaphore MAD when SMPs are not supported

- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
fix for #4188532: FW burn with flint (mft 4.30) has much longer time for FW burn per module for BM vs other systems (Croc, Gorilla)"
Description: When checking whether the PCI VSC spaces are supported, the status bit is 1, indicating that they are, which causes each failure in reading/writing to go to the function check_syndrome that tells us whether we should switch to the PCI VSC space. this overhead is what caused this bug. Since FW has a bug where they ignore the MSB of the space, each time we attempt to check whether a PCI VSC space is supported, what's actually written is the core VSC space, hence the status FW returns is 1 and we wrongly conclude they are supported. Fixed by adding a check to see whether what's written to the space field in VSC is indeed what we attempted to write. …
> fix for #4188532: FW burn with flint (mft 4.30) has much longer time

- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
Description: Due to new values for lock state in secure_host register we need to change current check from bool based (if != 0) to a more specific check.
During MCC init we check if state == 1 which means general lock state. During MCC burn we check for specific block according to the given component ID for update.
Issue: 4122407
> [flint][fw_comps_mgr] Support new state of secure_host register

- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
Description: added support to ZF mode in ConnectX7 and BlueField3
HLD: https://confluence.nvidia.com/pages/viewpage.action?pageId=2855575683
Issue: 4148208
> [CX7][BF-3] - add support to Zombiefish mode

- mvpd/mvpd.c
fix for "when VPD length is aligned on a 4B boundary, mstvpd fails due "-E- Failed to parse VPD from 21:00.0!"
Description: mvpd_len was not calculated correctly: It always missed the 1-byte length of the end tag. this was masked by the fact that mvpd_get_raw_vpd() calls my_vpd_read() and always reads 4 bytes at a time, so when the vpd len is not aligned on a 4B boundary, the 4B read covered the extra byte needed with the end tag len since it is only 1 byte. but when the vpd len is aligned on a 4B boundary, mvpd_len is calculated by reading all the VPD, yet not the end tag, which causes this error: "-E- Failed to parse VPD from 21:00.0!"
Tested flows: mstvpd 21:00.0
Issue: 4209502
> fix for "when VPD length is aligned on a 4B boundary, mstvpd fails"

- mtcr_freebsd/mtcr_ul.c
fix for "[MSTFLINT] Bug SW #4215561: [mstflint][freebsd] building mstflint for freebsd from master devel is broken"
Description:fixed compilation issue
Tested OS:freeBSD
Tested devices:n/a
Tested flows:./autogen.sh && ./configure && make
Issue:4215561
> fix for "[MSTFLINT] Bug SW #4215561: [mstflint][freebsd] build issue"

- flint/subcommands.cpp
- flint/subcommands.h
Description:
* adding to flint -d <dev> hw query a "TBS, BP[3:0]" field that displays the bits as they exist in the register status
Tested devices: ConnectX6DX, ConnectX8
Tested flows:
* flint -d <dev> -ocr hw query
Known gaps (with RM ticket): no
Issue: 4174429
Change-Id: I84fa36d191284f223cff16f28219241327e38289
> [ConnectX-8] External WP# for CX8

- include/mtcr_ul/mtcr.h
- include/mtcr_ul/mtcr_com_defs.h
- include/mtcr_ul/mtcr_mf.h
- mtcr_freebsd/Makefile.am
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/Makefile.am
- mtcr_ul/mtcr_common.c
- mtcr_ul/mtcr_common.h
- mtcr_ul/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
We dont yet have a way to check whether we should access the old or new PCI core address space. So if we get an error, we should try the other one.
> Set the correct address space in case of failure

- tools_layouts/fs5_image_layout_layouts.c
- tools_layouts/fs5_image_layout_layouts.h
Description: updated boot component layout
Tested devices: cx8
Tested flows: flint -ocr q
Issue: 4238977
> [mstflint][query] is broken for oberon branch on cx8

- common/Makefile.am
- common/tools_json.cpp
- common/tools_json.h
- mlxconfig/Makefile.am
- mlxconfig/mlxcfg_ui.cpp
- mlxconfig/mlxcfg_ui.h
- mlxfwupdate/server_request.cpp
- mlxfwupdate/server_request.h
Description: declaration on vars such as "Json::Reader oJsonReader{};" cause many coverity issues in the code - a wrapper was implemented
Tested devices: CX-6
Tested flows: N/A
Issue: 4215440
Change-Id: Ib8cbc44bfaa21ab001f6bc850fc60585dd310b65
> [Coverity] make a common wrapper for json reader and use one time

- include/mtcr_ul/mtcr_mf.h
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_icmd_cif.c
fix for "[MFT] Bug SW #4220920: [pci_space][freebsd] MFE_BAD_PARAMS after reading from pci space address"
Description:
1. initialize mf->pxir_vsec_supp in mopen by checking VSC address_space support of the VSC address_spaces that belong to PCI. This is opposed to before where we based the support on the dev ID, which then caused unexpected behaviour in scenarios where the dev ID was not initialized.
2. aligned the "swap and retry" mechanism to Linux implementation.
3. after reading from the PCI config space the dword at offset VSC+0x10 - extract the syndrome bit.
4. changed mset_addr_space implementation to be aligned to Linux implementation
5. in _set_addr_space we now directly write to the space field instead of reading the whole dwrod, modifying it and writing back. this is because …
> fix for "[MFT] Bug SW #4220920: [pci_space][freebsd] MFE_BAD_PARAMS after reading from pci space address"

- mlxfwops/lib/fs4_ops.cpp
Description: merge problem - pading by memset with wrong size. the size will be calculated in thte future.
Tested flows: mstflint -i /mswg/tmp/cx7_image.bin --private_key /mswg/projects/mft/regression/bug_repro/mstflint_bug/mstflint_bug_private_key.bin --key_uuid 233a4d49b0839447f2fdf9f7a347a22e --public_key /mswg/projects/mft/regression/bug_repro/mstflint_bug/mstflint_bug_public_key.bin rsa_sign
Known gaps (with RM ticket): no
Issue: 4257791
> [HTOC] removing padding to a value whose size is unknown

- include/mtcr_ul/mtcr_com_defs.h
- kernel/mst_main.c
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
[MTCR_UL][CX8] - fix for mstdump failing on cr-error
Description: moved syndrome and syncrome_code check to mtcr_pciconf_mread4 so we can know how many bytes we read successfully until we reached ADDRESS_OUT_OF_RANGE (i.e. the indication we need to swap from CORE to PCI or vice versa). did the same for the mwrite4_block_pciconf, mread4 and mwrite4. In addition added a check whether we were able to read the syndrome and syndrome_code successfully. changed variable names to more meaningful names and added debug prints.
Tested OS:linux, freebsd
Tested devices:cx8
Tested flows:
mstmcra 81:00.0 0x140780
mstmcra 81:00.0 0x140780,16
validated output for 0x14780 which should be 0xb2 and for 0x30011c which should be 0 according to PCI team.
mstflint/small_utils/mstmcra  81:00.0 0x140780,16 …
> [MTCR_UL][CX8] - fix for mstdump failing on cr-error

- mlxlink/modules/mlxlink_cables_commander.cpp
- mlxlink/modules/mlxlink_cables_commander.h
Description: 1. Don't enforce page validation for R\W operations. 2. Add CMIS pages to --cable --dump according to SPEC logic Issue:3678078
Reviewed By:HarelK
Change-Id: I458bef9e56301237e14ce7d313e9b005869dbd22
> Title:[Feature][CMIS_5.2] Support for CMIS 5.2 R\W and EEPROM dumps

- mflash/mflash.c
- mflash/mflash_pack_layer.h
Description: in ZF mode, recovery is done via the "recovery" address_space in VSC and not the "crspace" address_space. base address of flash GW is 0x10 in VSC recovery address_space, so when reading/writing: address should be base_flash_gw + <relative address of component>
Tested OS:n/a
Tested devices:n/a
Tested flows:n/a
Issue:4231024
> [ZF mode] - align flash gw base address

- mlxlink/modules/mlxlink_cables_commander.cpp
Description:Page 0x2F was missing from valid pages. Issue:4272664
Reviewed By:HarelK,MajdH
Change-Id: I1f807eee0638dc9116d6e17a4679b0b0565ac935
> Title:[Bug][MLXLINK] Page 0x2F is not printed in dump

- configure.ac
The AC_ARG_ENABLE() autoconf macro is sometimes incorrect in mstflint.
See:
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.72/autoconf.html#Package-Options
A construct such as:
AC_ARG_ENABLE(fw-mgr,
[  --enable-fw-mgr         Enable compiling mstfwmanager tool and features],
[enable_fw_mgr="yes"],
[enable_fw_mgr="no"])
sets the "action-if-given" to always forces the feature to "yes".
This can lead to the inverse of the desired effect. That is, calling:
./configure --disable-fw-mgr
or
./configure --enable-fw-mgr=no
will result to enable the feature. The only way to actually disable the
feature is to currently call "./configure" without the argument, to use
the default value set to "no".
This commit fixes the issue by consistently making all
"action-if-given" to use …
> Fix configure arg enable

- mlxlink/modules/mlxlink_commander.cpp
Description:
Tested OS:
Tested flows:
Issue:
> mlxlink | bug fix for show_eye crashing on GR100

- dev_mgt/tools_dev_types.c
- mtcr_ul/fwctrl.c
- mtcr_ul/mtcr_ul_com.h
This PR fixes various errors that occurred for me while trying to build the `mstflint` tools on the `master_devel` branch.
I used the following configure arguments: `--enable-fw-mgr --disable-inband --enable-adb-generic-tools`.
> fwctrl, dev_mgmt: fix build errors

- common/bit_slice.h
- mstdump/crd_main/mstdump.c
- mtcr_ul/mtcr_gpu.c
- mtcr_ul/mtcr_gpu.h
- mtcr_ul/mtcr_ul_icmd_cif.c
- mvpd/mvpd.c
- reg_access/reg_access.h
../common/bit_slice.h:64:5: error: cannot use keyword 'false' as enumeration constant
64 |     false = 0,
|     ^~~~~
../common/bit_slice.h:64:5: note: 'false' is a keyword with '-std=c23' onwards
../common/bit_slice.h:67:23: error: 'bool' cannot be defined via 'typedef'
67 | typedef unsigned char bool;
|                       ^~~~
../common/bit_slice.h:67:23: note: 'bool' is a keyword with '-std=c23' onwards
../common/bit_slice.h:67:1: warning: useless type name in empty declaration
67 | typedef unsigned char bool;
| ^~~~~~~
> Fix build failure with Fedora 43

- small_utils/mtserver.c
Fix the following build failure:
mtserver.c: In function ‘main’:
mtserver.c:849:17: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
849 |     PREP_SIGNAL(mySignal);
|                 ^~~~~~~~
|                 |
|                 void (*)(void)
mtserver.c:116:53: note: in definition of macro ‘PREP_SIGNAL’
116 | #define PREP_SIGNAL(signal_handler) signal(SIGPIPE, signal_handler);
|                                                     ^~~~~~~~~~~~~~
In file included from mtserver.c:149:
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
| …
> mtserver: Fix build failure

- resourcetools/resourcedump_lib/src/filters/include_exclude_segments_filter.h
Include cstdint to avoid the following build failure:
In file included from strip_control_segments_filter.h:36,
from strip_control_segments_filter.cpp:33:
include_exclude_segments_filter.h:52:52: error: 'uint16_t' was not declared in this scope
52 |                                  const std::vector<uint16_t> selected_segment_ids,
|                                                    ^~~~~~~~
include_exclude_segments_filter.h:41:1: note: 'uint16_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
40 | #include <sstream>
+++ |+#include <cstdint>
41 |
include_exclude_segments_filter.h:52:60: error: template argument 1 is invalid
52 |                                  const std::vector<uint16_t> selected_segment_ids,
| …
> resourcedump_lib: Fix build failure

- mtcr_ul/mtcr_ul_com.c
Avoids the warning:
suggest parentheses around assignment used as truth value [-Wparentheses]
> mtcr_ul: Avoid assignment in parentheses

- mlxfwops/lib/components/fs_comps_ops.cpp
- mlxfwops/lib/components/fs_synce_ops.cpp
- mlxfwops/lib/fs5_ops.cpp
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fw_ops.cpp
Remove names of unused parameters, or mark them as unused.
Avoid a long series of warnings in case -Wunused-parameter is used or implied.
> Remove names of unused parameter names

- flint/subcommands_linkx.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mlxconfig/mlxcfg_generic_commander.cpp
- mlxfwops/lib/fsctrl_ops.cpp
Description: checking secure host state prior to locking MCC udpate handle
> [Umbriel][CX7] NSM protection modes 2 does NOT block flint update

- mlxfwops/lib/fsctrl_ops.cpp
This avoids a warning:
output may be truncated copying 208 bytes from a string of length 208 [-Wstringop-truncation]
The buffer has one extra character. Or is this actually an extra space to make sure the buffer ends with a null?
Not sure of this.
> Pass the proper buffer size to strncpy

- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
[mtcr] - added a check whether recovery spcae in VSC is supported before attempting to read from it.
Description: when we determine whether a device is in ZF mode, before attempting to read from the recovery space in VSC, check whether FW supports this space. if FW does not support this space the device is not in ZF mode.
> mtcr sync from master

- mlxfwops/lib/signature_manager.h
- mlxfwops/lib/signature_manager_factory.h
Description: N/A
Tested devices: CX8
Tested flows: flint query on CX8 model
Issue: 3891066
Change-Id: I0a6dd04bf773ecfbf98bc01822a1400d9135cc4e
> Add CX8 dev id to mlxfwops signature manager

- mlxfwops/lib/fs4_ops.cpp
Description: missing definitions for security version accessibility
Tested devices: cx8
Tested flows: mstflint -d <dev> -ocr q full
Issue: 4361666
> [CX8] When device is in LF Relay, mstflint query fails to run

- configure.ac
- flint/cmd_line_parser.cpp
- flint/flint.cpp
- flint/flint_params.cpp
- flint/flint_params.h
- include/mtcr_ul/mtcr.h
- include/mtcr_ul/mtcr_com_defs.h
- include/mtcr_ul/mtcr_mf.h
- mstdump/crd_main/mstdump.c
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ib_ofed.c
- mtcr_ul/mtcr_ul.c
- mtcr_ul/mtcr_ul_com.c
- mtcr_ul/mtcr_ul_com.h
- mtcr_ul/mtcr_ul_icmd_cif.c
- small_utils/mcra.c
- small_utils/mtserver.c
Description: Added the i2c interface infrastructure to support embedded i2c devices (/dev/i2c-X). For devices up until the secure generation - secondary address 0x48 is used both in livefish devices and functional devices. For devices of the secure generation (ConnectX7, Quantum2 and above) - secondary address 0x48 is used for livefish devices. 0x47 is for functional devices. Added to mstflint tool the option to set the desired secondary address from the command line.
Supported OSes: Linux.
Tested devices: Spectrum3, Quantum2
Tested flows:
on secure and non-secure device (i.e. using 0x47 and 0x48). read:
mstflint/small_utils/mstmcra /dev/i2c-2 0xf0014
mstflint/small_utils/mstmcra /dev/i2c-2 0xf0014,16 write and check the value was indeed written: …
> Porting MFT's legacy infrastructure for i2c interface.

- flint/subcommands.cpp
- mflash/mflash.c
- mflash/mflash.h
- mflash/mflash_access_layer.h
- mflash/mflash_common_structs.h
- mlxfwops/lib/flint_io.cpp
- mlxfwops/lib/flint_io.h
Description: for ISSI flash:
* flint hw query will display SRWD
Tested devices: CX-6, CX-8
Tested flows:
Used mcra commands to:
* get the value of SRWD and then make sure I get the same value in flint hw query
Issue: 4103192
> [flint][hw set/query][SRWD]add support for SRWD bit

- flint/subcommands.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- fw_comps_mgr/fw_comps_mgr.h
- mlxfwops/lib/fs3_ops.cpp
- mlxfwops/lib/fs3_ops.h
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fsctrl_ops.h
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
Description: added support for set_key and hw_access command on secured devices
Tested devices: Cx5 Cx7
Tested flows:
flint set_key
flint hw_access enable
flint hw_access disable
Issue: 4382555
> [flint][set_key] dosen't work on secure devices

- mlxconfig/mlxcfg_generic_commander.cpp
- mlxsign_lib/mlxsign_com_def.h
- mtcr_py/cmtcr.c
Make sure initializing the variable with MlxSign::INVALID_TYPE before its first use and avoid a random behavior.
> Fix an uninitialized variable in GenericCommander::sign()

- kernel/mst_main.c
Declare functions that are not exported as local. Otherwise we get an error that they don't have a pre-declaration.
> statify local functions

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_commander.cpp
Description:
Tested flows:
Issue: 4274650
> mlxlink | display per lane BER info

- mflash/mflash_access_layer.c
- mflash/mflash_access_layer.h
Description: added the correct interpretation of BP bits when -ocr flag is not used during flint hw query
Tested devices: CX-6, Spectrum2
Tested flows: flint hw set Flash0.WriteProtected, flint -ocr hw set Flash0.WriteProtected, flint hw query, flint -ocr hw query
Issue: 4376790
Change-Id: I3b77aebac25686dfac15c498e4a80e213115574d
> [BugFix] Flash TBS,BP on Switches Issue

- kernel/mst_main.c
Don't consider the result of ioremap a pointer that can include an errno (was that the rationale?).
Avoids an error of considering a pointer as an int.
> Test return of ioremap with non-NULL

- mlxfwops/lib/flint_base.h
Description: Changing the reboot message to a generic reboot message
Tested devices: NA
Tested flows: NA
Issue: NA
> [flint] Changing the reboot message to a generic reboot message

- mlxlink/modules/mlxlink_amBER_collector.cpp
- mlxlink/modules/mlxlink_amBER_collector.h
- mlxlink/modules/mlxlink_commander.cpp
- mlxlink/modules/mlxlink_commander.h
- mlxlink/modules/mlxlink_enums.h
- mlxlink/modules/mlxlink_maps.cpp
- mlxlink/modules/mlxlink_maps.h
- mlxlink/modules/mlxlink_ui.cpp
- mlxlink/modules/mlxlink_user_input.cpp
- mlxlink/modules/mlxlink_user_input.h
- mlxlink/modules/mlxlink_utils.cpp
- mlxlink/modules/mlxlink_utils.h
- mlxlink/modules/printutil/mlxlink_record.cpp
- mlxlink/modules/printutil/mlxlink_record.h
Description:
support querying available ports in one table:
added support to view multi port info.
added support to view multi port module info.
new flags:
--smpi or --show-multi-port-info
--smpmi or --show-multi-port-module-info
Tested OS:
Tested flows:
Issue:
> mlxlink | add support for displaying multi port tables

- flint/subcommands.cpp
Description: the comparison in printFs4OrNewerUids for GUID was on the same current objects, this has been fixed the comparison is between the current and the orig
Tested devices: cx8
Tested flows: flint -d  /dev/mst/mt4131_pciconf0 query full
Issue: 4170267
Change-Id: Iedd2472bd9e8f68424d012146aa1f86d46f763d7
> Fixing GUID comparison between orig and current for query command

- mlxtokengenerator/mlxtkngenerator.cpp
Description: missing include fixed
Issue: 4410103
> [msttokengenerator] --enable-i2c configure build flag not working

- mstflint.spec.in
fix for "[MSTFLINT] Bug SW #4410113: enable i2c flag not in mstflint tarball"
Description: added a definition for the flag and the condition to include it in the spec file (to mstflint.spec.in).
Issue: 4410113
> fix for "[MSTFLINT] Bug SW #4410113: enable i2c flag not in mstflint

- mtcr_ul/mtcr_ul_com.c
- mtcr_ul/mtcr_ul_com.h
Fix for mstflint query over I2C
Description: fixed the hierarchy of the writing functions.
1. mtcr_i2c_mwrite_chunks:
Splits the data into 32-byte chunks, calls mwrite_i2c_chunk for each chunk.
Returns total bytes written or error.
2. mwrite_i2c_chunk:
Handles a single chunk of data (32 bytes). Converts endianness, sets up I2C addressing, and calls mwrite_i2cblock for the actual write.
Returns total bytes written or error.
mwrite_i2cblock:
Performs the I2C write ioctl.
Returns the ioctl rc in case of failure.
Adjusted the read functionality to be of the same format.
Tested devices: Spectrum2 (appssw-15)
Tested flows:
./flint/mstflint -d /dev/i2c-2 q
./mstdump/crd_main/mstregdump /dev/i2c-2
Issue: 36597033
> Fix for mstflint query over I2C

- mlxfwops/lib/fs4_ops.cpp
Description: added init for verify flow
Tested devices: CX8 encrypted
Tested flows: mstflint -d <dev> v
Issue: 4424563
> [mstflint][livefish][CX8] Unable to verify device

- pldmlib/pldm_utils.cpp
addressing issue:
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I. -I../common -Wall -W -g -MP -MD -pipe -fPIC -DPLDMLIB_EXPORT -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -DHAVE_TERMIOS_H -DHAVE_SYS_PCI_H -DNO_RDMEM -DMST_UL -MT pldm_utils.lo -MD -MP -MF .deps/pldm_utils.Tpo -c pldm_utils.cpp  -fPIC -DPIC -o .libs/pldm_utils.o
In file included from pldm_utils.cpp:21:
pldm_utils.h:39:6: warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword
39 | enum class DescriptorType : uint16_t
| ~~~~ ^~~~~
|      -----
pldm_utils.h:39:27: error: found ':' in …
```
> pldmlib/pldm_utils.cpp: fix missing header

- pldmlib/pldm_utils.h
Currently, the following errors occur when attempting to compile the latest `mstflint` release using the `musl` toolchain:
```
In file included from pldm_utils.cpp:21:
pldm_utils.h:63:22: error: 'u_int32_t' was not declared in this scope; did you mean 'uint32_t'?
63 | std::string NumToStr(u_int32_t num);
|                      ^~~~~~~~~
|                      uint32_t
pldm_utils.h:66:80: error: 'u_int16_t' has not been declared
66 | void ComponentIdentifierToStringValue(ComponentIdentifier componentIdentifier, u_int16_t field, std::string& value);
|                                                                                ^~~~~~~~~
pldm_utils.h:67:74: error: 'u_int16_t' has not been declared
67 | void ComponentIdentifierToValue(ComponentIdentifier componentIdentifier, u_int16_t …
```
> pldmlib: include <sys/types.h> for musl compatibility

- mlxlink/modules/mlxlink_cables_commander.cpp
Description:Changed when to access SFP module high i2c address. Issue:4445516
Reviewed By:HarelK
Change-Id: I3893eda73cca11af7ddebbea91369e30159daf82
> Title:[Bug][MLXLINK] SFP module wrong high address behavior

- include/mtcr_ul/mtcr.h
- include/mtcr_ul/mtcr_com_defs.h
- mtcr_freebsd/mtcr_ul.c
- mtcr_ul/mtcr_ul.c
- mtcr_ul/mtcr_ul_icmd_cif.c
- small_utils/mtserver.c
- tools_res_mgmt/tools_res_mgmt.c
Description: when accessing the device configuration space via GW (either VSC GW or PCI BAR0 GW), we address the ICMD semaphore as a whole DWORD.
This is in contrast to direct access to the device configuration space (MST_PCI) where the ICMD semaphore is 1 bit long.
Issue:4436228
> ICMD semaphore62 lock fix

- mlxfwops/lib/fw_ops.cpp
Description: fixed written bytes overflow
Tested devices: Cx8 in LF
Tested flows: mstflint -d <dev> -ocr wb <image> 0x0
Issue: 4477144
> [Mstflint] WB a full image on Device does not report status

- flint/subcommands.cpp
- fw_comps_mgr/fw_comps_mgr.cpp
- mflash/mflash.c
- mlxconfig/mlxcfg_generic_commander.cpp
- mlxfwops/lib/fs3_ops.cpp
- mlxfwops/lib/fs5_ops.cpp
- mlxfwops/lib/fs5_ops.h
- mlxfwops/lib/fsctrl_ops.cpp
- mlxfwops/lib/fsctrl_ops.h
- mlxfwops/lib/fw_ops.cpp
- mlxfwops/lib/fw_ops.h
- mlxfwupdate/image_access.cpp
- mlxlink/modules/mlxlink_commander.h
Added the following commits that were missing:
f189a2523734d516d3c8671918cbd813273010de - [flint] Binary Compare for CX8
530cd3c7d422d1b95155d06e3e293a0612804f2f - Revert "[flint] Set pci-link-disable bit when sending MFRL after FW update"
c38c970015bf66fbe8a74ab1e522254447d16bca - [flint][mflash] Flash Vendor Size Issue
c09515bddfe58d81fe78afacdbd5d672970b4d5c - [flint]Added support for burning extracted image
e007a66e67a8deffa9b2f0b97dfc6a901e7162ad - [mlxfwmanager][flint] Validate out of range info size for MCQI
04b60377e651d2c1df0e7b2cc9d1d140ea3ce1bd - [AWS-NVL][GB200] mlxfwmanager query with old firmware returns incorrect available version
> Aligning mstflint_4_31_0_gb200 to MFT's mft_4_31_0_release branch

- fw_comps_mgr/fw_comps_mgr.cpp
- kernel/mst_main.c
- mft_utils/mft_sig_handler.c
- mlxconfig/mlxcfg_param.h
- mlxfwops/lib/fw_ops.cpp
- mtcr_ul/mtcr_ul_com.c
added the following commits that are present in MFT's mft_4_32_0_oberon branch but missing in the mstflint branch:
83a2446a5434d028e61986f4c8ca5530e9032391 - [ConnectX-8] add support to PCIe Switch
22610ac970c306deb8dc1475e276478b3b974737 - [mlxtokengenerator] Badly formed XML
cfb89c86f94c9d801e1a064e3143079384d5cf85 - Fix Customer bug for handle sighup
568ca1479e05034a5b91eb725041020a0fcdde81 - [mlxfwmanager][flint] Validate out of range info size for MCQI
> Align april

- flint/subcommands.cpp
Description: remove the encapsulation header from the comparison section
Tested devices: /dev/mst/mt542_pciconf0
Tested flows: flint -d /dev/mst/mt542_pciconf0 -i /mswg/projects/tool_vfn/bin_images_cache/10_06_2025/GILBOA/900-9X81E-00EX-ST0_Ax~MT_0000001167.bin -ocr v
Issue: 4493174
Change-Id: I482ab3ae6bfe8c9ecd5e6a0ace7e4b0fff435bd2
> [flint][BC] Supports binary comparison for FS5 in LF mode

- mtcr_ul/mtcr_ul_com.c
add support for CX9 PCIe switch (NIC hidden)
Issue: 4395744
> add support for CX9 PCIe switch (NIC hidden)

- mlxlink/modules/mlxlink_utils.cpp
Description:
Tested OS:
Tested flows:
Issue:
> mlxlink | PCIE | bug fix for pci gen-6 showing as 'N/A'

- mlxlink/modules/mlxlink_commander.cpp
Description:
Tested OS:
Tested flows:
Issue:
> mlxlink | bug fix for wrong fields were ported to mstflint.

- small_utils/mstfwreset.py
Description: when MROQ is not supported reset_sync isn't updated from flags
> mlxfwreset | wrong sync chosen during reset

- cable_access/cdb_cable_access.h
- cable_access/cdb_cable_commander.cpp
- cable_access/cdb_cable_commander.h
- flint/subcommands.cpp
- flint/subcommands.h
Description: flint query command on cable mst devices will perform CDB 100 and print FW information to the screen
Tested OS: linux x86_64
Tested devices: LinkX modules
Tested flows:
1) discover cables using mstcable_discovery
2) flint -d <cable dev> q
Issue: 4549503
> [flint] support CDB 100 for cable query

- mlxlink/modules/mlxlink_cables_commander.cpp
Description:
Tested OS:
Tested flows:
Issue:
> mlxlink | bug fix for missing multiplier for tx_bias_lane in DDMinfo

- small_utils/mlxfwresetlib/mlxfwreset_utils.py
Description: we get a "Failed to get device PCI Address" error since the device name has "vfio-" that is not handled.
Issue: 4578529
> mstfwreset | vfio device failure

- include/mtcr_ul/mtcr_mf.h
- mlxreg/mlxreg_lib/mlxreg_lib.cpp
- mtcr_ul/fwctrl.c
Description: print the syndrome value in case it is set and access register has failed when running mstreg tool.
Issue:4598390
> [Design] - [META] [GB200/300] mstreg failure doesn't print FW syndrome

- mst_utils/mdevices_info.c
Description: need to skip pcie switch only of VSC is not supported.
Issue:4575398
Issue:4609737
> cherry-pick: fix for cx8 pcie switch discovery

- fw_comps_mgr/fw_comps_mgr_abstract_access.h
- fw_comps_mgr/fw_comps_mgr_dma_access.h
Description: added initialization for members in AbstractComponentAccess class and removed unrequired members from derived class
Tested flows: build
Issue: 4620059
> mstflint crash during burn (software bug. uninitialized variables)

- cable_access/cdb_cable_commander.cpp
Description: fixed burn completion print
Tested devices: 3rd party module
Tested flows: mstflint -d <module> -i <image> --activate burn
Issue: 4644225
> [flint][modules][3rd party] module fw burn stops at 99%

- configure.ac
- include/mtcr_ul/mtcr_com_defs.h
- mst_utils/mdevices_info.c
- mstflint.spec.in
- mtcr_ul/Makefile.am
- mtcr_ul/mtcr_ul_com.c
Add --enable-vfio configure flag to make VFIO library optional.
Tested flows:
build the project with and without --enable-vfio and then:
- nm /swgwork/ssela/workspace/mstflint2/mstflint/mtcr_ul/.libs/libmtcr_ul.a | grep -i vfio
- mdevices_info -v
Issue: 4648559
Change-Id: Ie24dfe2a5a0153155b1a534cc0a1b0aee2928e55
> Add --enable-vfio configure flag to make VFIO library optional
